{
  "hash": "1e3760dee2deb8f02a009b76c5283578",
  "result": {
    "engine": "knitr",
    "markdown": "# Das Newsvendor-Modell {#sec-newsvendor}\n\n::: {.lernziele}\n**Lernziele**\n\nNach diesem Kapitel können Sie...\n\n- das **Newsvendor-Problem** als typische Einperioden-Bestellmengenentscheidung unter Nachfrageunsicherheit einordnen und von mehrperiodigen Bestandsproblemen abgrenzen,\n- **Unterdeckungs-** und **Überdeckungskosten** aus einer gegebenen Erlös- und Kostenstruktur herleiten,\n- die **kritische Verhältniszahl (Critical Ratio)** aus einer Grenzkostenbetrachtung ableiten und ökonomisch interpretieren,\n- die optimale Bestellmenge sowohl bei **diskreter** als auch bei **stetiger (normalverteilter)** Nachfrage berechnen,\n- den Zusammenhang zwischen kritischer Verhältniszahl und **Servicegrad** erklären,\n- eine eigene, mehrzeilige R-Funktion schreiben, die ein komplettes Entscheidungsmodell kapselt,\n- numerische Wurzelfindung (`uniroot()`) und Optimierung (`optimize()`) als Alternative zu geschlossenen Lösungsformeln einsetzen,\n- eine Sensitivitätsanalyse durch Vektorisierung eines Modells über einen Parametervektor durchführen und deren Ergebnis grafisch aufbereiten.\n:::\n\n## Einperiodige Entscheidungen unter Unsicherheit\n\nIn Kapitel 6 haben wir gelernt, wie sich Nachfrageunsicherheit mit Wahrscheinlichkeitsverteilungen beschreiben lässt und wie man mit `rnorm()`, `dnorm()`, `pnorm()` und `qnorm()` Aussagen über normalverteilte Zufallsgrößen trifft. Auch das Prinzip der Monte-Carlo-Simulation mit `replicate()` und die empirische Verteilungsfunktion `ecdf()` wurden dort eingeführt. In diesem Kapitel nutzen wir genau dieses Instrumentarium, um eine der zentralen Entscheidungssituationen des Supply Chain Managements zu lösen: die Frage, wie viel von einem Produkt bestellt oder produziert werden soll, wenn die Nachfrage erst *nach* der Entscheidung bekannt wird und eine Korrektur der Menge während der Verkaufsperiode nicht mehr möglich ist.\n\nDieses Problem heißt **Newsvendor-Modell** (auch *Newsboy-Problem* oder *Einperioden-Bestandsmodell*), benannt nach dem klassischen Beispiel eines Zeitungsverkäufers, der jeden Morgen entscheiden muss, wie viele Exemplare einer Tageszeitung er einkauft, bevor er die tatsächliche Nachfrage des Tages kennt. Die mathematische Struktur des Problems wurde bereits in den 1950er-Jahren von @arrow1951optimal formal untersucht und ist seither eines der am häufigsten verwendeten Modelle der Bestandsplanung [@cachon2024matching; @silver2017inventory]. Charakteristisch für alle Anwendungen ist:\n\n- Es wird **eine einzige Bestell- oder Produktionsentscheidung** vor Beginn der Verkaufsperiode getroffen.\n- **Innerhalb der Periode** ist keine Nachbestellung möglich — Angebot und Nachfrage treffen erst am Ende der Periode endgültig aufeinander.\n- Die Nachfrage der Periode ist zum Entscheidungszeitpunkt **unsicher**, aber ihre Verteilung ist bekannt (z. B. aus historischen Verkaufsdaten geschätzt).\n- Nicht verkaufte Einheiten haben am Ende der Periode einen **geringeren Wert** als ursprünglich kalkuliert (Rabattverkauf, Entsorgung, Rückgabe an den Hersteller) — und zu wenig bestellte Einheiten führen zu **entgangenem Deckungsbeitrag**.\n\nDamit ist das Newsvendor-Modell das mikroökonomische Fundament für sehr viel weitreichendere Fragestellungen: Wie hoch sollte der Sicherheitsbestand in einem mehrperiodigen Lager sein? Wie groß sollte die Kapazität einer Fertigungslinie sein? Wie viele Zimmer sollte ein Hotel für eine bestimmte Nacht anbieten? Wir werden in diesem Kapitel sehen, dass alle diese Fragen im Kern dieselbe formale Struktur besitzen.\n\n## Fallbeispiel: Sushi-Boxen im Supermarkt\n\nZur Veranschaulichung begleiten wir das gesamte Kapitel mit einem durchgehenden Beispiel: Die **SushiFresh GmbH**, ein regionaler Hersteller frischer Sushi-Boxen im Rhein-Main-Gebiet, beliefert täglich mehrere Supermarkt-Filialen mit frisch produzierten Sushi-Boxen. Der zeitliche Ablauf eines Verkaufstages sieht für jede Filiale wie folgt aus:\n\n1. **7 Uhr:** Die Sushi-Boxen werden frisch vorbereitet und vor Ladenöffnung an die jeweilige Filiale geliefert.\n2. **8 Uhr:** Der Verkauf im Supermarkt beginnt. Nachlieferungen während des Tages sind ausgeschlossen — die produzierte Menge ist für den gesamten Tag fix.\n3. **19 Uhr:** Nicht verkaufte Boxen werden von SushiFresh wieder abgeholt.\n4. **20 Uhr:** Die Restware wird rabattiert verkauft, gespendet oder entsorgt — ein regulärer Verkauf am Folgetag ist aus Gründen der Lebensmittelsicherheit nicht mehr zulässig.\n\nDie zentrale unternehmerische Entscheidung fällt bereits am Morgen, lange bevor die tatsächliche Tagesnachfrage der jeweiligen Filiale bekannt ist: **Wie viele Sushi-Boxen sollte SushiFresh je Filiale produzieren?**\n\n### Erlös- und Kostenstruktur\n\nFür eine einzelne Sushi-Box gelten folgende, vereinfachte Werte:\n\n| Größe | Bedeutung | Wert |\n|---|---|---:|\n| Verkaufspreis $p$ | Erlös je verkaufter Sushi-Box | 10 € |\n| Herstell- und Lieferkosten $c$ | Kosten je vorbereiteter Sushi-Box | 5 € |\n| Restwert $v$ | Erlös bei Abendrabatt bzw. Verwertung | 2 € |\n\nFür ökonomisch sinnvolle Anwendungen des Modells muss stets $p > c > v$ gelten: Läge der Restwert $v$ nicht unterhalb der Herstellkosten $c$, gäbe es keinen Anreiz, die Bestellmenge überhaupt zu begrenzen — man könnte beliebig viel produzieren, da selbst unverkaufte Ware immer noch mindestens kostendeckend verwertet würde. Läge umgekehrt der Verkaufspreis $p$ nicht oberhalb der Herstellkosten $c$, würde sich der Verkauf grundsätzlich nicht lohnen.\n\nAus diesen drei Größen leiten wir zwei zentrale Kostenkategorien ab, die im weiteren Verlauf des Kapitels immer wieder auftauchen:\n\n::: {.definition}\n**Definition: Unterdeckungs- und Überdeckungskosten**\n\nDie **Unterdeckungskosten** $c^u$ (*underage cost*) entsprechen dem entgangenen Deckungsbeitrag je Einheit, die nicht verkauft werden konnte, weil zu wenig bestellt wurde:\n$$c^u = p - c$$\n\nDie **Überdeckungskosten** $c^o$ (*overage cost*) entsprechen dem Verlust je Einheit, die am Ende der Periode nicht verkauft wurde:\n$$c^o = c - v$$\n\nFür unser Sushi-Beispiel ergibt sich: $c^u = 10 - 5 = 5\\ \\text{€}$ und $c^o = 5 - 2 = 3\\ \\text{€}$.\n:::\n\nBeide Größen sind *Opportunitätskosten* — es fließt kein Geld in Höhe von $c^u$ oder $c^o$ tatsächlich ab, sondern es handelt sich um entgangenen bzw. verlorenen Deckungsbeitrag im Vergleich zur jeweils bestmöglichen Entscheidung. Genau dieses Spannungsfeld zwischen \"zu wenig\" und \"zu viel\" bestellen ist der Kern des Newsvendor-Problems.\n\n## Herleitung der Gewinnfunktion\n\nBezeichnen wir mit $D$ die (zufällige) Tagesnachfrage und mit $q$ die vom Lieferanten festgelegte Bestellmenge, lassen sich zwei Situationen unterscheiden.\n\n**Fall 1 — Überdeckung ($q > D$):** Es wird mehr produziert als nachgefragt. Verkauft werden genau $D$ Einheiten, während $q - D$ Einheiten zum Restwert verwertet werden müssen. Der Deckungsbeitrag beträgt\n$$P(D,q) = D \\cdot c^u - (q - D) \\cdot c^o.$$\n\n**Fall 2 — Unterdeckung ($q < D$):** Es wird weniger produziert als nachgefragt. Da nicht mehr Ware zur Verfügung steht, als produziert wurde, werden genau $q$ Einheiten verkauft — die überschießende Nachfrage $D - q$ bleibt unbedient und der zugehörige Deckungsbeitrag geht verloren. Es gilt\n$$P(D,q) = q \\cdot c^u.$$\n\nBeide Fälle lassen sich mithilfe der *positiven Teil*-Funktion $(x)^+ := \\max(x,0)$ zu einer einzigen, für beliebige Werte von $D$ und $q$ gültigen Gewinnfunktion zusammenfassen:\n$$\nP(D,q) = c^u \\cdot \\min(D,q) - c^o \\cdot (q-D)^+.\n$$\n\nDa $\\min(D,q) = D - (D-q)^+$ gilt (die verkaufte Menge entspricht der Nachfrage abzüglich der nicht bedienten Fehlmenge), lässt sich die Gewinnfunktion äquivalent auch so schreiben:\n$$\nP(D,q) = \\underbrace{D \\cdot c^u}_{\\text{maximal möglicher DB}} - \\underbrace{(D-q)^+ \\cdot c^u}_{\\text{Fehlmengenkosten}} - \\underbrace{(q-D)^+ \\cdot c^o}_{\\text{Überbestandskosten}}.\n$$\n\nDiese Schreibweise macht die ökonomische Logik besonders deutlich: Ausgehend vom größtmöglichen Deckungsbeitrag $D \\cdot c^u$, den man erzielen würde, wenn man die Nachfrage exakt träfe, werden zwei Arten von Kosten abgezogen — die Fehlmengenkosten bei zu geringer und die Überbestandskosten bei zu hoher Bestellmenge. Da $D$ zum Entscheidungszeitpunkt eine Zufallsvariable ist, betrachten wir den **Erwartungswert** über alle möglichen Nachfragerealisationen:\n$$\nE[P(q)] = \\mu \\cdot c^u - c^u \\cdot E\\big[(D-q)^+\\big] - c^o \\cdot E\\big[(q-D)^+\\big],\n$$\nwobei $\\mu = E[D]$ der Erwartungswert der Nachfrage ist. Da der erste Term $\\mu \\cdot c^u$ nicht von $q$ abhängt, ist die Maximierung des erwarteten Gewinns äquivalent zur Minimierung der erwarteten Fehlmengen- und Überbestandskosten:\n$$\n\\min_q\\ E[C(q)] = c^u \\cdot E\\big[(D-q)^+\\big] + c^o \\cdot E\\big[(q-D)^+\\big].\n$$\n\nBevor wir diese Optimierung formal lösen, implementieren wir das Modell für den diskreten Fall selbst in R — das schärft das Verständnis der Formel erheblich mehr, als sie nur zu lesen.\n\n::: {.r-exkurs}\n**R-Exkurs: Eine Modellfunktion kapseln**\n\nIn Kapitel 2 haben Sie gelernt, eigene Funktionen mit `function()` zu schreiben. Bisher waren das meist kurze Hilfsfunktionen mit wenigen Zeilen. Für komplexere Modelle — wie das Newsvendor-Modell — lohnt es sich, das *gesamte* Berechnungsschema in einer einzigen, gut dokumentierten Funktion zu kapseln: Eingabeparameter hinein, alle Zwischengrößen berechnet, und am Ende ein strukturiertes Ergebnis (typischerweise eine `list()`) zurückgegeben. Genau nach diesem Muster ist auch die Funktion `newsvendor_normal()` in `R/scm_functions.R` aufgebaut, die wir später in diesem Kapitel noch verwenden werden.\n\nWir bauen die diskrete Variante jetzt Schritt für Schritt selbst:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)  # dplyr, tibble, ggplot2, purrr\n\n#' Newsvendor-Modell bei diskreter Nachfrage\n#'\n#' Berechnet fuer eine Menge diskreter Nachfrageszenarien den erwarteten\n#' Gewinn je Bestellmenge sowie die nach der Fraktilregel optimale\n#' Bestellmenge.\n#'\n#' @param nachfrage           aufsteigend sortierter Vektor moeglicher\n#'                            Nachfragewerte (die Bestellmengen-Kandidaten)\n#' @param wahrscheinlichkeit  Vektor der zugehoerigen Eintrittswahrscheinlichkeiten\n#' @param verkaufspreis       Erloes je verkaufter Einheit (p)\n#' @param herstellkosten      Kosten je produzierter/beschaffter Einheit (bewusst\n#'                            nicht \"c\" genannt, da c() in R fuer Vektoren reserviert ist!)\n#' @param restwert            Erloes je nicht verkaufter Einheit (v)\n#' @return Liste mit Kostenparametern, vollstaendiger Ergebnistabelle und\n#'         optimaler Bestellmenge\nnewsvendor_diskret <- function(nachfrage, wahrscheinlichkeit,\n                                verkaufspreis, herstellkosten, restwert) {\n\n  # -- 1. Eingaben pruefen ---------------------------------------------------\n  stopifnot(\n    length(nachfrage) == length(wahrscheinlichkeit),\n    abs(sum(wahrscheinlichkeit) - 1) < 1e-8,   # Wahrscheinlichkeiten summieren zu 1\n    all(diff(nachfrage) > 0),                   # nachfrage muss aufsteigend sortiert sein\n    verkaufspreis > herstellkosten,\n    herstellkosten > restwert\n  )\n\n  # -- 2. Kostenparameter ableiten -------------------------------------------\n  cu <- verkaufspreis - herstellkosten   # Unterdeckungskosten c^u\n  co <- herstellkosten - restwert        # Ueberdeckungskosten c^o\n  cr <- cu / (cu + co)                   # kritische Verhaeltniszahl (critical ratio)\n\n  # -- 3. erwarteter Gewinn fuer eine gegebene Bestellmenge q ----------------\n  # Innere Hilfsfunktion: nutzt die Variablen aus der umgebenden Funktion\n  # (cu, co, nachfrage, wahrscheinlichkeit) und ist deshalb nur lokal gueltig.\n  gewinn_bei_q <- function(q) {\n    gewinn_je_szenario <- cu * pmin(nachfrage, q) - co * pmax(q - nachfrage, 0)\n    sum(wahrscheinlichkeit * gewinn_je_szenario)  # Erwartungswert\n  }\n\n  # -- 4. alle Nachfrageszenarien als Bestellmengen-Kandidaten durchrechnen --\n  erwarteter_gewinn <- vapply(nachfrage, gewinn_bei_q, numeric(1))\n\n  # -- 5. kumulierte Wahrscheinlichkeiten fuer die Fraktilregel --------------\n  kumuliert <- cumsum(wahrscheinlichkeit)\n\n  # -- 6. optimale Bestellmenge: kleinstes q mit F(q) >= kritischer Quote ----\n  q_stern <- nachfrage[min(which(kumuliert >= cr))]\n\n  # -- 7. Ergebnis als benannte Liste zurueckgeben ----------------------------\n  list(\n    cu             = cu,\n    co             = co,\n    cr             = cr,\n    tabelle        = tibble(\n      bestellmenge       = nachfrage,\n      wahrscheinlichkeit = wahrscheinlichkeit,\n      kumuliert          = kumuliert,\n      erwarteter_gewinn  = erwarteter_gewinn\n    ),\n    q_stern        = q_stern,\n    gewinn_optimum = gewinn_bei_q(q_stern)\n  )\n}\n```\n:::\n\n\nNun wenden wir die Funktion auf ein bewusst kleines, vereinfachtes Miniaturbeispiel an — etwa einen Testverkauf in einer kleinen Filiale, für die noch keine verlässliche Verteilungsannahme getroffen werden kann. Aus Verkaufshistorie, Wochentag, Wetterprognose und aktuellen Aktionen wurden für diesen Testfall vier mögliche Nachfrageszenarien geschätzt:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsushi <- newsvendor_diskret(\n  nachfrage          = c(30, 40, 50, 60),\n  wahrscheinlichkeit = c(0.20, 0.35, 0.30, 0.15),\n  verkaufspreis      = 10,\n  herstellkosten     = 5,\n  restwert           = 2\n)\n\nsushi$tabelle |>\n  knitr::kable(\n    digits = c(0, 2, 2, 1),\n    col.names = c(\"Bestellmenge q\", \"P(D=q)\", \"F(q)\", \"E[Gewinn | q]\")\n  )\n```\n\n::: {.cell-output-display}\n\n\n| Bestellmenge q| P(D=q)| F(q)| E[Gewinn &#124; q]|\n|--------------:|------:|----:|------------------:|\n|             30|   0.20| 0.20|                150|\n|             40|   0.35| 0.55|                184|\n|             50|   0.30| 0.85|                190|\n|             60|   0.15| 1.00|                172|\n\n\n:::\n:::\n\n\nDer erwartete Gewinn steigt zunächst von 30 auf 50 Sushi-Boxen an und fällt danach wieder — ein typisches Muster für Newsvendor-Probleme: Sowohl zu geringe als auch zu hohe Bestellmengen verringern den erwarteten Gewinn. Die Funktion identifiziert **50** Sushi-Boxen als optimale Bestellmenge mit einem erwarteten Gewinn von **190** € pro Tag. Im nächsten Abschnitt leiten wir her, *warum* genau diese Menge optimal ist.\n:::\n\n## Diskrete Nachfrage: Die Fraktilregel\n\nWarum wählt unsere Funktion gerade die kleinste Bestellmenge, deren kumulierte Wahrscheinlichkeit $F(q)$ eine bestimmte Schwelle überschreitet? Die Antwort liefert eine **Grenzbetrachtung**: Wir fragen uns, ob es sich lohnt, die Bestellmenge um eine zusätzliche Einheit zu erhöhen.\n\n- Mit Wahrscheinlichkeit $1 - F(q)$ liegt die tatsächliche Nachfrage *über* $q$. In diesem Fall wird die zusätzliche Einheit verkauft und vermeidet eine Fehlmenge — der erwartete Grenzgewinn beträgt $c^u \\cdot (1 - F(q))$.\n- Mit Wahrscheinlichkeit $F(q)$ liegt die Nachfrage bei höchstens $q$. In diesem Fall bleibt die zusätzliche Einheit unverkauft — der erwartete Grenzverlust beträgt $c^o \\cdot F(q)$.\n\nEs lohnt sich, die Bestellmenge zu erhöhen, solange der erwartete Grenzgewinn den erwarteten Grenzverlust übersteigt, also solange $c^u \\cdot (1-F(q)) > c^o \\cdot F(q)$ gilt. Am **Optimum** sind Grenzgewinn und Grenzverlust der letzten bestellten Einheit gerade ausgeglichen:\n\n::: {.definition}\n**Definition: Kritische Verhältniszahl (Critical Ratio)**\n\n$$\nc^u \\cdot \\big(1 - F(q^*)\\big) = c^o \\cdot F(q^*) \\quad \\Longleftrightarrow \\quad F(q^*) = \\underbrace{\\frac{c^u}{c^u + c^o}}_{=: CR} \\quad \\Longleftrightarrow \\quad q^* = F^{-1}(CR).\n$$\n\nDie **kritische Verhältniszahl** $CR$ gibt an, welcher Anteil der Nachfrageverteilung höchstens von der optimalen Bestellmenge abgedeckt werden sollte. Sie hängt ausschließlich vom *Verhältnis* der Unter- zu den Überdeckungskosten ab, nicht von deren absoluter Höhe.\n:::\n\nFür unser Sushi-Beispiel ergibt sich $CR = 5/(5+3) = 0{,}625$. Bei **diskreter** Nachfrage ist $F$ eine Treppenfunktion, sodass $F(q) = CR$ im Allgemeinen für kein einziges $q$ exakt erfüllt ist. Die korrekte Entscheidungsregel lautet deshalb: Wähle die **kleinste** Bestellmenge $q$, deren kumulierte Wahrscheinlichkeit $F(q)$ mindestens $CR$ erreicht.\n\n| Nachfrage $D$ | $P(D=d)$ | $F(d)$ |\n|---:|---:|---:|\n| 30 | 0,20 | 0,20 |\n| 40 | 0,35 | 0,55 |\n| 50 | 0,30 | 0,85 |\n| 60 | 0,15 | 1,00 |\n\nDa $F(40) = 0{,}55 < 0{,}625 \\le F(50) = 0{,}85$, ist $q^* = 50$ Sushi-Boxen die optimale Bestellmenge — exakt das Ergebnis, das unsere Funktion `newsvendor_diskret()` im vorherigen Abschnitt bereits durch vollständiges Durchrechnen aller erwarteten Gewinne gefunden hat. Diese Übereinstimmung ist kein Zufall, sondern die Bestätigung, dass die Fraktilregel und das direkte Ausrechnen des erwarteten Gewinns *dasselbe* Optimierungsproblem lösen — einmal über eine geschlossene Entscheidungsregel, einmal über vollständige Enumeration.\n\nDie kritische Verhältniszahl erlaubt zudem eine anschauliche Fallunterscheidung:\n\n- **$c^u < c^o$:** Fehlmengen sind günstiger als Überbestände $\\Rightarrow$ $CR < 0{,}5$ $\\Rightarrow$ $q^*$ liegt **unterhalb** des Medians der Nachfrage — es lohnt sich, eher knapp zu bestellen.\n- **$c^u = c^o$:** Beide Fehlerarten sind gleich teuer $\\Rightarrow$ $CR = 0{,}5$ $\\Rightarrow$ $q^*$ entspricht dem **Median** der Nachfrage.\n- **$c^u > c^o$:** Fehlmengen sind teurer als Überbestände $\\Rightarrow$ $CR > 0{,}5$ $\\Rightarrow$ $q^*$ liegt **oberhalb** des Medians — es lohnt sich, eher großzügig zu bestellen.\n\n## Stetige Nachfrage: Die Normalverteilung\n\nIn der Praxis liegt Nachfrage selten in Form weniger diskreter Szenarien vor, sondern wird — wie in Kapitel 6 besprochen — häufig durch eine stetige Verteilung angenähert, meist die Normalverteilung $D \\sim N(\\mu, \\sigma^2)$. Die SushiFresh GmbH beliefert inzwischen sechs Supermarkt-Filialen im Rhein-Main-Gebiet, deren Tagesnachfrage sich je nach Einzugsgebiet und Filialgröße deutlich unterscheidet. Wir betrachten im Folgenden die größte dieser Filialen, **Frankfurt**, für die aus der dokumentierten Verkaufshistorie eine Tagesnachfrage von $\\mu = 280$ Boxen mit einer Standardabweichung von $\\sigma = 55$ Boxen geschätzt wurde (bei unveränderter Kostenstruktur $c^u = 5\\,$ €, $c^o = 3$ €, denn Verkaufspreis, Herstellkosten und Restwert sind produktbezogene und nicht filialspezifische Größen). Es handelt sich um dieselbe Filiale, die auch in Kapitel 6 im Kontext des Pooling-Effekts des Sicherheitsbestands über das SushiFresh-Filialnetz betrachtet wird.\n\nDa die Normalverteilung eine streng monoton wachsende, stetige Verteilungsfunktion $F$ besitzt, existiert die Umkehrfunktion $F^{-1}$ exakt — die Fraktilregel muss hier nicht mehr näherungsweise über eine Treppenfunktion, sondern kann direkt ausgewertet werden. Wie in Kapitel 6 gilt für die Standardisierung $Z = (D-\\mu)/\\sigma \\sim N(0,1)$, sodass sich $q^*$ mit dem Quantil der Standardnormalverteilung ausdrücken lässt, das `qnorm()` liefert:\n\n$$\nq^* = \\mu + \\sigma \\cdot \\Phi^{-1}(CR) = \\mu + \\sigma \\cdot z^*, \\qquad z^* = \\Phi^{-1}(CR).\n$$\n\nUm auch die erwarteten Kosten am Optimum angeben zu können, benötigen wir die Erwartungswerte $E[(D-q)^+]$ und $E[(q-D)^+]$ für normalverteilte Nachfrage. Mit der **Einheits-Normalverlustfunktion** $L(z) = \\varphi(z) - z\\cdot(1-\\Phi(z))$ — wobei $\\varphi$ die Dichte der Standardnormalverteilung ist — lassen sich beide Erwartungswerte kompakt darstellen:\n$$\nE\\big[(D-q)^+\\big] = \\sigma \\cdot L(z), \\qquad E\\big[(q-D)^+\\big] = \\sigma \\cdot L(-z), \\qquad z = \\frac{q-\\mu}{\\sigma}.\n$$\nSetzt man dies in die erwartete Kostenfunktion ein und wertet sie an der Optimalstelle $z = z^*$ aus (wo $\\Phi(z^*) = CR$ per Konstruktion gilt), heben sich die von $z^*$ abhängigen Terme gegenseitig auf, und es verbleibt die bemerkenswert einfache Formel\n\n$$\nE\\big[C(q^*)\\big] = (c^u + c^o) \\cdot \\sigma \\cdot \\varphi(z^*).\n$$\n\nGenau diese beiden Formeln — für $q^*$ und $E[C(q^*)]$ — implementiert die Funktion `newsvendor_normal()` in `R/scm_functions.R`, die Sie zu Beginn dieses Kapitels bereits kennengelernt haben. Rechnen wir unser Beispiel nach:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu_nachfrage    <- 280  # Erwartungswert der Tagesnachfrage der Filiale Frankfurt (Boxen)\nsigma_nachfrage <- 55   # Standardabweichung der Tagesnachfrage der Filiale Frankfurt (Boxen)\n\ncu <- 5   # Unterdeckungskosten (wie im diskreten Fall)\nco <- 3   # Ueberdeckungskosten\n\ncr      <- cu / (cu + co)                 # kritische Verhaeltniszahl\nz_stern <- qnorm(cr)                      # Standardnormal-Quantil\nq_stern_normal <- mu_nachfrage + sigma_nachfrage * z_stern\n\n# erwartete Fehlmengen- und Ueberbestandskosten am Optimum\nkosten_optimum <- (cu + co) * sigma_nachfrage * dnorm(z_stern)\n\nq_stern_normal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 297.5252\n```\n\n\n:::\n\n```{.r .cell-code}\nkosten_optimum\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 166.8459\n```\n\n\n:::\n:::\n\n\nMit $CR = 0{,}625$ ergibt sich $z^* = \\Phi^{-1}(0{,}625) \\approx 0{,}319$ und damit $q^* = 280 + 55 \\cdot 0{,}319 \\approx 297{,}5$ Sushi-Boxen. Da nur ganze Boxen produziert werden können, würde man in der Praxis auf $q^* = 298$ aufrunden. Die erwarteten Fehlmengen- und Überbestandskosten am Optimum betragen rund $166{,}8\\,$€ pro Tag, sodass der erwartete Gewinn $E[P(q^*)] = \\mu \\cdot c^u - E[C(q^*)] \\approx 280 \\cdot 5 - 166{,}8 \\approx 1233{,}2\\,$€ pro Tag beträgt.\n\nZur Kontrolle vergleichen wir unser eigenes Ergebnis direkt mit der fertigen Funktion aus `R/scm_functions.R`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"../R/scm_functions.R\")\n\nergebnis_fertig <- newsvendor_normal(\n  mu = mu_nachfrage, sigma = sigma_nachfrage,\n  p = 10, c = 5, s = 2\n)\n\nergebnis_fertig$q_star       # sollte mit q_stern_normal uebereinstimmen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 297.5252\n```\n\n\n:::\n\n```{.r .cell-code}\nergebnis_fertig$exp_profit   # erwarteter Gewinn am Optimum\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1233.154\n```\n\n\n:::\n:::\n\n\nDie folgende Abbildung veranschaulicht die Nachfrageverteilung zusammen mit der optimalen Bestellmenge: Die grün eingefärbte Fläche links von $q^*$ entspricht der kumulierten Wahrscheinlichkeit $F(q^*) = CR$, also dem Anteil der Tage, an denen die Bestellmenge ausreicht.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnachfrage_grid <- tibble(\n  d      = seq(mu_nachfrage - 4 * sigma_nachfrage,\n               mu_nachfrage + 4 * sigma_nachfrage,\n               length.out = 300),\n  dichte = dnorm(d, mean = mu_nachfrage, sd = sigma_nachfrage)\n)\n\nggplot(nachfrage_grid, aes(x = d, y = dichte)) +\n  geom_area(\n    data = filter(nachfrage_grid, d <= q_stern_normal),\n    fill = \"#52B788\", alpha = 0.45\n  ) +\n  geom_area(\n    data = filter(nachfrage_grid, d >= q_stern_normal),\n    fill = \"#D97B29\", alpha = 0.30\n  ) +\n  geom_line(linewidth = 1, colour = \"#1F2933\") +\n  geom_vline(\n    xintercept = q_stern_normal,\n    linetype = \"dashed\", colour = \"#0B6E4F\", linewidth = 1\n  ) +\n  annotate(\n    \"text\", x = q_stern_normal, y = max(nachfrage_grid$dichte) * 0.95,\n    label = paste0(\"q* = \", round(q_stern_normal, 1)),\n    hjust = -0.1, colour = \"#0B6E4F\", fontface = \"bold\"\n  ) +\n  labs(\n    x = \"Nachfrage D (Sushi-Boxen pro Tag)\",\n    y = \"Dichte f(D)\",\n    title = \"Kritische Verhältniszahl als Flächenanteil unter der Dichtefunktion\"\n  ) +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Dichte der normalverteilten Sushi-Nachfrage der Filiale Frankfurt mit optimaler Bestellmenge](07_das-newsvendor-modell_files/figure-html/fig-newsvendor-normal-1.png){#fig-newsvendor-normal width=672}\n:::\n:::\n\n\nEin methodischer Exkurs sei an dieser Stelle erlaubt: Anstatt die Formel für $q^*$ direkt zu verwenden, ließe sich der erwartete Gewinn $E[P(q)]$ auch näherungsweise per **Monte-Carlo-Simulation** bestimmen — genau wie in Kapitel 6 eingeführt. Man würde mit `rnorm()` eine sehr große Zahl zufälliger Tagesnachfragen ziehen, für jede Ziehung den realisierten Gewinn gemäß der Gewinnfunktion $P(D,q)$ berechnen und anschließend über alle Wiederholungen mitteln (etwa mit `replicate()`). Für eine hinreichend große Anzahl von Simulationsläufen konvergiert dieser simulierte Mittelwert gegen den hier analytisch berechneten Erwartungswert $E[P(q)]$ — ein guter Plausibilitätstest, wenn eine geschlossene Formel wie hier verfügbar ist, und die einzige praktikable Lösung, wenn sie es nicht ist.\n\n## Numerische Optimierung als Alternative zur geschlossenen Lösung\n\nFür die Normalverteilung konnten wir $q^*$ bequem über `qnorm()` bestimmen, weil ihre Verteilungsfunktion eine bekannte Umkehrfunktion besitzt. Bei vielen praktisch relevanten Verteilungen — etwa einer Lognormal-, Gamma- oder empirisch aus Daten geschätzten Verteilung — existiert keine geschlossene Form für $F^{-1}$. In solchen Fällen hilft numerische  **Optimierung**, wie sie im folgenden Exkurs eingeführt wird.\n\n::: {.r-exkurs}\n**R-Exkurs: `uniroot()` und `optimize()` statt analytischer Lösung**\n\nDie Bedingung $F(q^*) = CR$ aus der Fraktilregel lässt sich als **Nullstellenproblem** auffassen: Gesucht ist der Wert $q$, für den die Funktion $g(q) = F(q) - CR$ gleich null wird. Die Funktion `uniroot()` findet genau eine solche Nullstelle in einem vorgegebenen Intervall — ganz ohne dass wir die Umkehrfunktion von $F$ explizit kennen müssten:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Zielfunktion: Differenz zwischen Verteilungsfunktion und kritischer Quote.\n# Bei Erfolg liefert uniroot() das q, fuer das diese Differenz null wird.\nzielfunktion_wurzel <- function(q) {\n  pnorm(q, mean = mu_nachfrage, sd = sigma_nachfrage) - cr\n}\n\nloesung_uniroot <- uniroot(\n  zielfunktion_wurzel,\n  interval = c(mu_nachfrage - 4 * sigma_nachfrage,\n               mu_nachfrage + 4 * sigma_nachfrage)\n)\n\nloesung_uniroot$root   # sollte (nahezu) mit q_stern_normal uebereinstimmen\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 297.5252\n```\n\n\n:::\n:::\n\n\nAlternativ lässt sich die erwartete Kostenfunktion $E[C(q)]$ auch **direkt minimieren**, ohne den Umweg über die Fraktilregel zu gehen — nützlich etwa, wenn man ausschließlich die Kostenfunktion kennt, nicht aber deren analytisches Minimum. `integrate()` berechnet dabei die Erwartungswerte $E[(D-q)^+]$ und $E[(q-D)^+]$ numerisch, und `optimize()` sucht anschließend das Minimum der Gesamtkostenfunktion:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nerwartete_kosten <- function(q) {\n  e_fehlmenge <- integrate(\n    function(d) (d - q) * dnorm(d, mean = mu_nachfrage, sd = sigma_nachfrage),\n    lower = q, upper = mu_nachfrage + 8 * sigma_nachfrage\n  )$value\n\n  e_ueberbestand <- integrate(\n    function(d) (q - d) * dnorm(d, mean = mu_nachfrage, sd = sigma_nachfrage),\n    lower = mu_nachfrage - 8 * sigma_nachfrage, upper = q\n  )$value\n\n  cu * e_fehlmenge + co * e_ueberbestand\n}\n\nloesung_optimize <- optimize(\n  erwartete_kosten,\n  interval = c(mu_nachfrage - 4 * sigma_nachfrage,\n               mu_nachfrage + 4 * sigma_nachfrage)\n)\n\nloesung_optimize$minimum   # optimale Bestellmenge\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 297.5252\n```\n\n\n:::\n\n```{.r .cell-code}\nloesung_optimize$objective # minimale erwartete Kosten\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 166.8459\n```\n\n\n:::\n:::\n\n\nBeide numerischen Verfahren liefern (bis auf minimale Rundungsabweichungen) dasselbe Ergebnis wie die geschlossene Formel $q^* = \\mu + \\sigma \\cdot \\Phi^{-1}(CR)$. Der Vorteil dieser Herangehensweise zeigt sich, sobald man `dnorm()`/`pnorm()` durch die Dichte- bzw. Verteilungsfunktion einer beliebigen anderen Verteilung ersetzt — die Struktur des Codes bleibt unverändert, während eine analytische Herleitung für jede neue Verteilung von Neuem geleistet werden müsste.\n:::\n\n## Kritische Verhältniszahl und Servicegrad\n\nDie kritische Verhältniszahl $CR = \\Phi(z^*)$ besitzt eine zweite, sehr praxisnahe Interpretation: Sie entspricht genau der Wahrscheinlichkeit, dass die Nachfrage die Bestellmenge **nicht** übersteigt, also dem sogenannten **Zyklus-Servicegrad** ($\\alpha$-Servicegrad) — dem Anteil der Perioden, in denen die gesamte Nachfrage aus der vorhandenen Menge gedeckt werden kann. Für unser Beispiel bedeutet $CR = 0{,}625$: An etwa 62,5 % aller Tage reicht die Bestellmenge $q^*$ aus, um die komplette Tagesnachfrage zu bedienen; an den übrigen rund 37,5 % der Tage kommt es zu einer (teilweisen) Fehlmenge.\n\nDieser Zusammenhang ist der Grund, warum das Newsvendor-Modell weit über Einperiodenprobleme hinaus Bedeutung hat: Die **Sicherheitsbestände** mehrperiodiger Lagerhaltungssysteme werden in der Praxis sehr häufig genau nach diesem Prinzip bemessen — man legt einen gewünschten Servicegrad fest (z. B. 95 %) und bestimmt daraus über $z = \\Phi^{-1}(\\text{Servicegrad})$ den erforderlichen Sicherheitsbestandsfaktor, wie es bereits in Kapitel 6 im Kontext des Pooling-Effekts anklang. Der Unterschied zum Newsvendor-Modell besteht lediglich darin, *woher* der Zielwert der kritischen Quote stammt: im Newsvendor-Modell wird er aus Kosten hergeleitet ($CR = c^u/(c^u+c^o)$), in vielen operativen Lagerhaltungssystemen dagegen häufig direkt als Managemententscheidung vorgegeben. Zu beachten ist außerdem, dass der hier betrachtete Zyklus-Servicegrad (Wahrscheinlichkeit *keiner* Fehlmenge) nicht mit dem **Fill Rate** verwechselt werden darf, der den Anteil der *mengenmäßig* gedeckten Nachfrage misst und in aller Regel höher ausfällt als der Zyklus-Servicegrad.\n\n## Sensitivitätsanalyse: Wie reagiert das Modell auf veränderte Parameter?\n\nBislang haben wir das Newsvendor-Modell für feste Werte von $\\mu$, $\\sigma$, $p$, $c$ und $v$ gelöst. In der Praxis interessiert oft, **wie empfindlich** die optimale Entscheidung auf Veränderungen dieser Parameter reagiert — etwa wenn der Verkaufspreis saisonal schwankt oder die Nachfrageschätzung mit Unsicherheit behaftet ist. Genau dafür eignet sich die **Vektorisierung**, die Sie bereits aus Kapitel 4 (`sapply()`) und Kapitel 5 (`purrr::map()`) kennen: Statt das Modell für einen einzelnen Parameterwert auszuwerten, wenden wir es auf einen ganzen Vektor möglicher Werte an.\n\n::: {.r-exkurs}\n**R-Exkurs: Sensitivitätsanalyse durch Vektorisierung**\n\nZunächst untersuchen wir, wie der erwartete Gewinn $E[P(q)]$ über ein feines Raster möglicher Bestellmengen verläuft — für die Filiale Frankfurt also für jede Menge zwischen 100 und 460 Boxen. Dazu kapseln wir die Gewinnformel aus dem Normalverteilungsfall in einer kleinen Funktion und werten sie mit `sapply()` für jeden Rasterpunkt aus:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Modellfunktion: erwarteter Gewinn bei gegebenem q (Normalverteilungsfall)\nerwarteter_gewinn_normal <- function(q, mu, sigma, cu, co) {\n  z <- (q - mu) / sigma\n  L <- function(z) dnorm(z) - z * (1 - pnorm(z))  # Einheits-Normalverlustfunktion\n  e_fehlmenge    <- sigma * L(z)\n  e_ueberbestand <- sigma * L(-z)\n  mu * cu - cu * e_fehlmenge - co * e_ueberbestand\n}\n\nq_raster <- seq(100, 460, by = 2)\n\n# sapply() wendet die Funktion auf jeden Wert des Rasters an\ngewinn_je_q <- sapply(\n  q_raster, erwarteter_gewinn_normal,\n  mu = mu_nachfrage, sigma = sigma_nachfrage, cu = cu, co = co\n)\n\nsensitivitaet_q <- tibble(bestellmenge = q_raster, erwarteter_gewinn = gewinn_je_q)\n\nggplot(sensitivitaet_q, aes(x = bestellmenge, y = erwarteter_gewinn)) +\n  geom_line(colour = \"#0B6E4F\", linewidth = 1) +\n  geom_vline(xintercept = q_stern_normal, linetype = \"dashed\", colour = \"#D97B29\") +\n  labs(\n    x = \"Bestellmenge q\", y = \"Erwarteter Gewinn E[P(q)] in €\",\n    title = \"Sensitivität des erwarteten Gewinns gegenüber der Bestellmenge\"\n  ) +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Erwarteter Gewinn in Abhängigkeit von der Bestellmenge q](07_das-newsvendor-modell_files/figure-html/fig-newsvendor-sensitivitaet-q-1.png){#fig-newsvendor-sensitivitaet-q width=672}\n:::\n:::\n\n\nDie Kurve bestätigt anschaulich, was wir bereits analytisch hergeleitet hatten: Der erwartete Gewinn ist eine **konkave** Funktion der Bestellmenge mit eindeutigem Maximum bei $q^*$ — sowohl deutlich kleinere als auch deutlich größere Mengen verringern den erwarteten Gewinn.\n\nIn einem zweiten Schritt untersuchen wir, wie stark sich die *optimale* Bestellmenge selbst verändert, wenn sich der Verkaufspreis $p$ ändert (z. B. durch saisonale Rabattaktionen). Dazu nutzen wir `purrr::map_dbl()`, das — analog zu `sapply()` — eine Funktion über einen Vektor iteriert und garantiert einen numerischen Vektor zurückgibt:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nherstellkosten <- 5   # bleibt konstant\nrestwert       <- 2   # bleibt konstant\npreise         <- seq(6, 16, by = 0.5)\n\nq_stern_je_preis <- purrr::map_dbl(preise, function(p) {\n  cu_tmp <- p - herstellkosten          # Unterdeckungskosten aendert sich mit p\n  cr_tmp <- cu_tmp / (cu_tmp + co)      # co bleibt unveraendert\n  mu_nachfrage + sigma_nachfrage * qnorm(cr_tmp)\n})\n\nsensitivitaet_preis <- tibble(preis = preise, q_stern = q_stern_je_preis)\n\nggplot(sensitivitaet_preis, aes(x = preis, y = q_stern)) +\n  geom_line(colour = \"#0B6E4F\", linewidth = 1) +\n  geom_point(colour = \"#0B6E4F\") +\n  labs(\n    x = \"Verkaufspreis p in €\", y = \"Optimale Bestellmenge q*\",\n    title = \"Je höher der Preis, desto größer die optimale Bestellmenge\"\n  ) +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Optimale Bestellmenge in Abhängigkeit vom Verkaufspreis](07_das-newsvendor-modell_files/figure-html/fig-newsvendor-sensitivitaet-preis-1.png){#fig-newsvendor-sensitivitaet-preis width=672}\n:::\n:::\n\n\nDie Grafik zeigt einen intuitiven Zusammenhang: Steigt der Verkaufspreis $p$, steigen die Unterdeckungskosten $c^u = p - c$ und damit auch die kritische Verhältniszahl $CR$ — der Lieferant sollte also tendenziell **mehr** bestellen, weil eine Fehlmenge nun teurer geworden ist. Solche Sensitivitätsanalysen sind in der Praxis oft mindestens so wertvoll wie der einzelne Optimalwert selbst, weil sie zeigen, wie robust eine Entscheidung gegenüber Schätzfehlern oder Marktschwankungen ist.\n:::\n\n## Anwendungsbereiche und Grenzen des Modells\n\nDas Newsvendor-Modell entfaltet seinen größten Nutzen dort, wo eine **Bedarfsglättung durch Lagerhaltung nicht möglich** ist und die Kostenparameter $c^u$ und $c^o$ hinreichend gut geschätzt werden können [@thonemann2023operations]. Typische Anwendungsbereiche sind:\n\n- **Saison- und Aktionsartikel** (Weihnachtsartikel, Modewaren einer Saison), bei denen eine Nachbestellung innerhalb der Saison praktisch ausgeschlossen ist,\n- **Frischwaren mit kurzer Haltbarkeit** (wie unser Sushi-Beispiel, aber auch Backwaren, Blumen oder Fertiggerichte),\n- **Tickets für Veranstaltungen oder Verkehrsmittel**, deren Kapazität am Veranstaltungs- bzw. Abfahrtstag fix ist,\n- **Kapazitätsplanung** in der Fertigung, wenn Kapazität nur einmalig vor Beginn einer Periode festgelegt werden kann.\n\nDarüber hinaus ist das Newsvendor-Modell — wie im vorigen Abschnitt gezeigt — die konzeptionelle Grundlage für die Berechnung kostenoptimaler Sicherheitsbestände in mehrperiodigen Lagerhaltungssystemen, was seine praktische Bedeutung weit über den Einzelfall der einmaligen Bestellentscheidung hinaushebt [@silver2017inventory].\n\nGleichwohl beruht das Modell auf einer Reihe von Annahmen, die in der Praxis kritisch zu prüfen sind: Es wird angenommen, dass die Nachfrageverteilung **bekannt und stationär** ist, dass der Entscheider **risikoneutral** ist (also ausschließlich den *erwarteten* Gewinn maximiert, ohne Risikoaversion gegenüber Verlusten zu berücksichtigen), dass keine **fixen Bestellkosten** anfallen und dass **eine** Bestellentscheidung tatsächlich die gesamte Periode abdeckt. Substitutionseffekte zwischen ähnlichen Produkten, Lerneffekte aus wiederholten Entscheidungen oder das Zusammenspiel mit vor- und nachgelagerten Stufen der Supply Chain — Themen, die uns im nächsten Kapitel zum Bullwhip-Effekt wieder begegnen werden — bleiben im Grundmodell unberücksichtigt und erfordern gegebenenfalls Erweiterungen [@cachon2024matching; @chopra2025supply].\n\n## Zusammenfassung\n\nDas Newsvendor-Modell beantwortet die Frage nach der optimalen Bestellmenge bei einer einmaligen Entscheidung unter unsicherer Nachfrage. Ausgangspunkt sind die Unterdeckungskosten $c^u = p - c$ und die Überdeckungskosten $c^o = c - v$, aus deren Verhältnis sich die kritische Verhältniszahl $CR = c^u/(c^u+c^o)$ ergibt. Diese entspricht sowohl dem Quantil der Nachfrageverteilung, das die optimale Bestellmenge festlegt ($q^* = F^{-1}(CR)$), als auch dem ökonomisch sinnvollen Servicegrad. Bei diskreter Nachfrage wird die kleinste Menge gewählt, deren kumulierte Wahrscheinlichkeit $CR$ mindestens erreicht; bei normalverteilter Nachfrage lässt sich $q^*$ direkt über $\\mu + \\sigma \\cdot \\Phi^{-1}(CR)$ berechnen. Methodisch haben Sie gelernt, ein vollständiges Entscheidungsmodell in einer eigenen R-Funktion zu kapseln, mit `uniroot()` und `optimize()` numerisch nach optimalen Lösungen zu suchen, wenn keine geschlossene Formel verfügbar ist, und mit vektorisierten Modellaufrufen (`sapply()`, `purrr::map_dbl()`) Sensitivitätsanalysen durchzuführen und grafisch darzustellen. Diese drei Techniken — eigene Modellfunktionen, numerische Optimierung und vektorisierte Sensitivitätsanalysen — werden uns in den folgenden Kapiteln immer wieder begegnen.\n\n::: {.kontrollfragen}\n**Kontrollfragen**\n\n1. Nennen Sie die vier charakteristischen Merkmale, die eine Entscheidungssituation zu einem Newsvendor-Problem machen. Warum eignet sich das Sushi-Beispiel dafür so gut?\n2. Definieren Sie Unterdeckungs- und Überdeckungskosten $c^u$ und $c^o$ anhand des Sushi-Beispiels in eigenen Worten. Warum handelt es sich dabei um Opportunitätskosten und nicht um tatsächliche Auszahlungen?\n3. Leiten Sie die kritische Verhältniszahl $CR = c^u/(c^u+c^o)$ mithilfe einer Grenzbetrachtung her (was passiert bei einer marginalen Erhöhung der Bestellmenge um eine Einheit?).\n4. Ein Zeitschriftenhändler kauft Exemplare für 2 € ein, verkauft sie für 5 € und kann unverkaufte Exemplare für 0,50 € an den Verlag zurückgeben. Die Tagesnachfrage folgt den Szenarien $\\{20, 30, 40\\}$ mit Wahrscheinlichkeiten $\\{0{,}3;\\ 0{,}5;\\ 0{,}2\\}$. Bestimmen Sie $c^u$, $c^o$, $CR$ und die optimale Bestellmenge.\n5. Warum liefert die Fraktilregel bei diskreter Nachfrage in der Regel keine exakte Gleichheit $F(q^*)=CR$, während sie es bei stetiger Nachfrage tut? Welche Entscheidungsregel gilt im diskreten Fall?\n6. Erklären Sie den Zusammenhang zwischen der kritischen Verhältniszahl und dem Zyklus-Servicegrad. Worin unterscheidet sich der Zyklus-Servicegrad vom Fill Rate?\n7. In welchen Situationen würden Sie `uniroot()` bzw. `optimize()` gegenüber einer analytischen Lösungsformel wie $q^* = \\mu + \\sigma \\cdot \\Phi^{-1}(CR)$ bevorzugen? Nennen Sie ein Beispiel für eine Nachfrageverteilung, bei der dies sinnvoll ist.\n8. Nennen Sie drei typische Anwendungsbereiche des Newsvendor-Modells sowie zwei zentrale Annahmen, die in der Praxis kritisch zu hinterfragen sind.\n:::\n",
    "supporting": [
      "07_das-newsvendor-modell_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}