{
  "hash": "8b98e2b3055560fb9c15ba770e25e854",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Module 3: Transportation Planning\"\nsubtitle: \"SCM — Bachelor 3rd Semester\"\nauthor: \"Prof. Dr. Thomas Kirschstein\"\ndate: last-modified\nformat:\n  revealjs:\n    theme: [default, ../../_extensions/scm-theme.scss]\n    slide-number: true\n    chalkboard: true\n    preview-links: auto\n    footer: \"SCM | Module 3 | HS RheinMain\"\n    logo: ../../data/logo.png\n    transition: slide\n    incremental: false\n    toc: true\n    toc-depth: 1\nexecute:\n  echo: false\n  warning: false\n  message: false\n---\n\n# Part 1: Transportation Fundamentals {background-color=\"#5E3EE1\"}\n\n## Learning Objectives\n\nAfter this module, you will be able to:\n\n- **Formulate** the Transportation Problem as a linear program\n- **Apply** Vogel's Approximation Method (VAM) to find near-optimal initial solutions\n- **Extend** the Transportation Problem to the Transshipment Problem\n- **Implement** LP-based transport optimisation in R\n- **Analyse** real-world transportation planning cases and mode selection decisions\n\n::: {.notes}\nModule 3 is the most quantitatively intensive module so far. The Transportation Problem (TP) is a network flow LP — one of the most studied problems in operations research. Stress to students that while the TP seems simple, it is the foundation for a vast family of models used in logistics, energy systems, and supply chain optimisation. The R implementation at the end connects theory directly to practice.\n:::\n\n---\n\n## Transportation in the SC Planning Matrix\n\n::: {.columns}\n::: {.column width=\"55%\"}\n**Transportation decisions across all three planning horizons:**\n\n**Strategic (Years)**\n\n- Modal choice (road vs. rail vs. sea vs. air)\n- Carrier contract structure and partner selection\n- DC network structure (which drives transport distances)\n- Outsourcing to 3PL vs. own fleet\n\n**Tactical (Months)**\n\n- Flow allocation across routes for a planning period\n- Seasonal capacity adjustments\n- Mode mix optimisation\n\n**Operational (Days/Weeks)**\n\n- Daily shipment routing and load planning\n- Carrier assignment and booking\n- Exception management (delays, damage)\n:::\n::: {.column width=\"45%\"}\n::: {.callout-note title=\"Cost Significance\"}\nTransport is typically **40–70% of total logistics cost** — the largest single cost driver in most supply chains.\n\n**European transport cost benchmarks:**\n\n| Mode | Cost (€/tkm) |\n|------|-------------|\n| Road (FTL) | 0.08–0.15 |\n| Rail (wagonload) | 0.03–0.07 |\n| Air freight | 1.50–4.00 |\n| Sea (container) | 0.004–0.015 |\n| Inland waterway | 0.02–0.05 |\n\n*tkm = tonne-kilometre*\n:::\n:::\n:::\n\n::: {.notes}\nThe cost significance of transport justifies the attention it receives in SC planning. Even a 5% reduction in transport cost through better routing and load planning can represent millions of euros for a mid-sized logistics network. At the same time, transport is the primary source of Scope 3 CO₂ emissions for most manufacturing companies — making it central to both the cost and sustainability agendas.\n:::\n\n---\n\n## Transportation Modes — Trade-offs\n\n| Mode | Speed | Cost | Capacity | Reliability | CO₂/tkm |\n|------|-------|------|----------|-------------|---------|\n| **Road (truck)** | Medium | Medium | Medium | High | High |\n| **Rail** | Slow | Low | High | Medium | Low |\n| **Air** | Fast | Very high | Low | Very high | Very high |\n| **Sea (ocean)** | Very slow | Very low | Very high | Low | Medium |\n| **Pipeline** | Continuous | Low | Very high | Very high | Very low |\n| **Inland waterway** | Slow | Very low | High | Medium | Very low |\n\n::: {.callout-tip title=\"Key Mode Selection Principle\"}\nMode selection is driven by three factors:\n\n1. **Product value density** (€/kg or €/m³)\n2. **Time sensitivity** of delivery\n3. **Volume** and regularity of shipments\n\nHigh value density + time-sensitive → Air. Low value density + bulk → Sea or rail. Medium + European distances → Road or rail intermodal.\n:::\n\n::: {.notes}\nRail freight in Germany is chronically underused relative to its environmental advantage — a political and infrastructure investment challenge. The German Masterplan Rail Freight (Masterplan Schienengüterverkehr) aims to double rail freight market share by 2030. From a supply chain perspective, rail's main drawback is poor last-mile connectivity (shunting yards + road drayage adds time and cost) and lower reliability due to shared passenger/freight track use.\n:::\n\n---\n\n## Value Density and Mode Selection\n\n::: {.columns}\n::: {.column width=\"55%\"}\n**Value density** = Product value / unit weight (€/kg)\n\n**Practical classification:**\n\n| Value Density | Category | Typical Mode |\n|--------------|----------|-------------|\n| > €500/kg | Pharmaceuticals, electronics, luxury | Air |\n| €50–500/kg | Consumer electronics, precision parts | Road / Air mix |\n| €5–50/kg | Packaged consumer goods, auto parts | Road / sea |\n| €0.5–5/kg | Industrial goods, food | Road / rail / sea |\n| < €0.5/kg | Bulk chemicals, grain, coal, ore | Sea / rail / pipeline |\n\n**Worked example:**\n\nA shipment of 100 kg worth €8,000 (€80/kg):\n- Air freight (Europe–USA): ~€4/kg = €400 (5% of value)\n- Sea freight: ~€0.50/kg = €50 (0.6% of value)\n- At €80/kg value density, sea is likely appropriate unless time-critical\n:::\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![Mode viability zones by value density and shipment size](03_network_design_files/figure-revealjs/unnamed-chunk-1-1.png){width=384}\n:::\n:::\n\n:::\n:::\n\n::: {.notes}\nThe value density concept elegantly captures why air freight is used for pharmaceuticals but never for steel: the transport cost as a percentage of product value is acceptable for high-density goods and absurd for low-density bulk materials. This has major implications for supply chain design: companies with high-value products can afford a responsive, air-capable supply chain, while companies with low-value products must optimise relentlessly for cost.\n:::\n\n---\n\n# Part 2: The Transportation Problem {background-color=\"#5E3EE1\"}\n\n## Transportation Problem — Formulation\n\n**Problem structure:**\n\n::: {.columns}\n::: {.column width=\"55%\"}\n**Given:**\n\n- $m$ **supply nodes** (plants/warehouses) with capacities $a_i$\n- $n$ **demand nodes** (customers) with requirements $b_j$\n- Unit transport cost $c_{ij}$ from node $i$ to node $j$\n\n**Decide:** Flow $x_{ij} \\geq 0$ (units shipped from $i$ to $j$)\n\n$$\\min \\sum_{i=1}^{m} \\sum_{j=1}^{n} c_{ij} x_{ij}$$\n\n**Subject to:**\n\n$$\\sum_{j=1}^{n} x_{ij} \\leq a_i \\quad \\forall i \\quad \\text{(supply)}$$\n\n$$\\sum_{i=1}^{m} x_{ij} = b_j \\quad \\forall j \\quad \\text{(demand)}$$\n\n$$x_{ij} \\geq 0$$\n:::\n::: {.column width=\"45%\"}\n**Key properties:**\n\n::: {.callout-note title=\"LP Properties\"}\n**Balanced TP:** If $\\sum_i a_i = \\sum_j b_j$, all supply constraints become equalities.\n\n**Total Unimodularity:** The constraint matrix is totally unimodular → LP relaxation always has an **integer optimal solution**.\n\nNo need for explicit integrality constraints — solving the LP gives integer flows automatically (for integer $a_i, b_j$).\n\nThis makes the TP computationally easy despite its apparent combinatorial structure.\n:::\n\n**Unbalanced TP:**\n\nIf $\\sum a_i > \\sum b_j$: add dummy demand node with zero cost.\n\nIf $\\sum a_i < \\sum b_j$: add dummy supply node (or use penalty cost M for unmet demand).\n:::\n:::\n\n::: {.notes}\nThe totally unimodular property is a deep result from network flow theory. It applies to all pure network flow problems (transportation, assignment, shortest path, max flow). The practical implication: TP instances with thousands of supply and demand nodes can be solved in milliseconds using specialised network simplex algorithms. This makes the TP one of the most practically useful models in operations research.\n:::\n\n---\n\n## Vogel's Approximation Method (VAM)\n\n**Regret-based greedy heuristic** (Reinfeld & Vogel, 1958)\n\n**Motivation:** Assign flows to the cheapest routes first — but also consider what we *lose* by not using them.\n\n**Algorithm:**\n\n::: {.columns}\n::: {.column width=\"60%\"}\n1. For each **row** (supply): compute regret = $c_{(2)} - c_{(1)}$ where $c_{(1)}, c_{(2)}$ are cheapest and 2nd-cheapest costs in that row\n2. For each **column** (demand): compute regret = analogous\n3. Select row or column with **maximum regret**\n4. **Allocate** maximum possible flow to the cheapest route in that row/column:\n   $$x_{ij} = \\min(a_i, b_j)$$\n5. **Update**: reduce capacities/demands; eliminate exhausted row/column\n6. **Repeat** from step 1 until all demand satisfied\n\n**Typical performance:** Solutions within **0–5% of optimum**. Much better than NW corner rule or Least Cost method on average.\n:::\n::: {.column width=\"40%\"}\n::: {.callout-tip title=\"Why Regret Matters\"}\nRegret = the cost *penalty* of not being able to use the cheapest route.\n\nHigh regret → we urgently need to use the cheapest route here, because the next-best option is much more expensive.\n\nLow regret → we can afford to be flexible.\n\nVAM prioritises the assignments where the cost of a wrong choice is highest — a sensible greedy criterion.\n:::\n:::\n:::\n\n::: {.notes}\nVAM is one of the most elegant heuristics in operations research. The regret concept is intuitive: if the cheapest and second-cheapest routes cost 10 and 11 (regret = 1), it doesn't matter much which we use. If they cost 5 and 50 (regret = 45), we desperately need to use the cheap one. VAM captures this urgency. In practice, VAM often finds the optimal solution or comes within 1–2%. It provides the starting basis for the Transportation Simplex method, which then finds the exact optimum.\n:::\n\n---\n\n## VAM Example — Pear Disk Drive Corporation\n\n**Three plants, four distribution centres. Supply exceeds demand → balanced by adding slack.**\n\n| Plant\\DC | Amarillo | Teaneck | Chicago | Sioux Falls | **Supply** |\n|-----------|---------|---------|---------|------------|-----------|\n| **Sunnyvale** | 250 | 420 | 380 | 280 | 45 |\n| **Dublin** | 1,280 | 990 | 1,440 | 1,520 | 120 |\n| **Bangkok** | 1,550 | 1,420 | 1,660 | 1,730 | 95 |\n| **Demand** | 80 | 78 | 47 | 55 | **260** |\n\n*Costs in USD per unit. Total supply = 260 = Total demand (balanced).*\n\n**VAM Step 1 — Compute row and column regrets:**\n\n| | Row Regrets | | | Col Regrets |\n|--|-------------|-|-|-------------|\n| Sunnyvale | 280−250 = **30** | | Amarillo | 1280−250 = **1030** |\n| Dublin | 1280−990 = **290** | | Teaneck | 1420−420 = **1000** |\n| Bangkok | 1660−1550 = **110** | | Chicago | 1440−380 = **1060** ← max |\n| | | | Sioux Falls | 1520−280 = **1240** ← max |\n\n**→ Column Chicago or Sioux Falls (tie) — select Sioux Falls. Assign Sunnyvale→Sioux Falls: min(45,55)=45 units. Sunnyvale exhausted.**\n\n::: {.notes}\nWalk through all VAM steps with students at the board. After iteration 1: Sunnyvale assigned to Sioux Falls (45 units). Remaining Sioux Falls demand = 10. Update regrets for remaining rows and columns. Continue until all demand satisfied. The final solution typically assigns Dublin primarily to Teaneck, Bangkok to Amarillo. The optimality check (using the MODI method / stepping stone) can be discussed briefly. Full solution: expected total cost ≈ $200,000–220,000 depending on rounding.\n:::\n\n---\n\n## R Code — Solving the Transportation Problem\n\n\n::: {.cell}\n\n```{.r .cell-code  code-line-numbers=\"1-5|7-9|11-13|15-18\"}\nlibrary(lpSolve)\n\n# Cost matrix: rows = supply nodes, cols = demand nodes\ncosts <- matrix(c(250,  420,  380,  280,\n                  1280, 990,  1440, 1520,\n                  1550, 1420, 1660, 1730),\n                nrow = 3, byrow = TRUE)\n\nsupply <- c(45, 120, 95)\ndemand <- c(80, 78, 47, 55)\n\n# Solve the transportation problem\nsol <- lp.transport(costs, direction = \"min\",\n                    row.signs  = rep(\"<=\", 3),\n                    row.rhs    = supply,\n                    col.signs  = rep(\">=\", 4),\n                    col.rhs    = demand)\n\n# Reshape solution\nflow_matrix <- matrix(sol$solution, nrow = 3, byrow = FALSE)\ndimnames(flow_matrix) <- list(\n  c(\"Sunnyvale\", \"Dublin\", \"Bangkok\"),\n  c(\"Amarillo\", \"Teaneck\", \"Chicago\", \"Sioux Falls\")\n)\nprint(flow_matrix)\ncat(\"Total cost: $\", sol$objval, \"\\n\")\n```\n:::\n\n\n::: {.callout-note title=\"Key R function: `lp.transport()`\"}\nFrom package `lpSolve`. Arguments:\n\n- `costs`: cost matrix ($m \\times n$)\n- `direction`: `\"min\"` or `\"max\"`\n- `row.signs`, `row.rhs`: supply constraints (use `\"<=\"` for capacities)\n- `col.signs`, `col.rhs`: demand constraints (use `\">=\"` for requirements)\n\nReturns `$solution` (flow matrix) and `$objval` (optimal total cost).\n:::\n\n::: {.notes}\nLive-code this in RStudio. The `lp.transport()` function is a wrapper around the general LP solver that is optimised for the transportation structure. The solution runs in milliseconds even for large instances. Encourage students to experiment with the cost matrix — e.g., what happens if Bangkok→Amarillo cost increases by 500? Does the optimal solution change? This builds intuition for sensitivity analysis.\n:::\n\n---\n\n## Exercise 3.1 — Battery Logistics {background-color=\"#361E47\"}\n\n**Scenario:** An EV battery manufacturer operates three warehouses supplying 11 automotive plants across Germany and Benelux.\n\n**Warehouse capacities (MWh/yr):**\n\n| Warehouse | Location | Capacity |\n|-----------|----------|---------|\n| W1 | Düren | 150,000 |\n| W2 | Harsewinkel | 50,000 |\n| W3 | Langenhagen | 100,000 |\n\n**Automotive plant demands** (given in course materials — total: 280,000 MWh/yr)\n\nPlants include: Wolfsburg, Emden, Hannover, Leipzig, Zwickau, Kassel, Brussels, Ghent, Antwerp, Stuttgart, Munich.\n\n**Tasks:**\n\n1. Build the **transport cost matrix**: use Haversine distance × €0.08/km per MWh\n2. **Formulate** the transportation LP (supply slightly exceeds demand → add dummy)\n3. Apply **VAM** to find an initial feasible solution\n4. Solve with **R/lpSolve** and compare to your VAM solution\n5. What is the annual transport cost? Where does it make sense to build a 4th warehouse?\n\n::: {.callout-tip title=\"Haversine Distance\"}\nAccounts for Earth's curvature. For Germany-scale distances: Euclidean error is <2%. Use haversine for precision. Package `geosphere` in R provides `distHaversine()`.\n:::\n\n::: {.notes}\nThis is a realistic exercise with actual German city coordinates. Provide students with a coordinate table (latitude/longitude) for all 11 plants and 3 warehouses. The Haversine calculation can be done in R using geosphere::distHaversine() or approximated with Euclidean distance on a Mercator projection. The \"where to build a 4th warehouse\" question connects back to Module 2 (Steiner-Weber / WLP) — a nice integration across modules.\n:::\n\n---\n\n# Part 3: Transshipment Problem {background-color=\"#5E3EE1\"}\n\n## From TP to Transshipment\n\n**Motivation:** Real distribution networks have **intermediate nodes** — cross-docks, ports, sorting hubs, intermodal terminals — that neither produce nor consume goods but relay them.\n\n::: {.columns}\n::: {.column width=\"55%\"}\n**Node types in the Transshipment Problem:**\n\n- $V_a$ — **Supply nodes**: $\\sum_j x_{aj} = a_k$ (supply $k$ shipped out)\n- $V_t$ — **Transshipment nodes**: flow in = flow out (no net gain/loss)\n- $V_d$ — **Demand nodes**: $\\sum_i x_{id} = b_l$ (demand $l$ received)\n\n**Classic applications:**\n\n- Port → Rail hub → Final delivery\n- Plant → Cross-dock → Retailer\n- Supplier → Consolidation centre → Customer\n- Airport hub-and-spoke networks\n:::\n::: {.column width=\"45%\"}\n```\nSupply Nodes    Trans. Nodes    Demand Nodes\n\n   P1 ──────→ [Hub 1] ──────→  C1\n    │              ↑             │\n    └──────→ [Hub 2] ──→  C2   │\n   P2 ──────→ [Hub 2] ──→  C3  │\n                    └──────────→ C1\n```\n\n**Key insight:** The Transshipment Problem can be **reduced to a standard TP** by duplicating each transshipment node as both a supply and demand node with large capacity $L = \\sum_i a_i$.\n:::\n:::\n\n::: {.callout-note title=\"Reduction to Standard TP\"}\nFor each transshipment node $t \\in V_t$:\n- Add \"supply\" capacity $L$ (absorbs incoming flow)\n- Add \"demand\" $L$ (re-ships outgoing flow)\n- Self-loop cost = 0 (goods that don't transship \"stay\" at the node)\n:::\n\n::: {.notes}\nThe transshipment problem generalises the TP to multi-echelon networks — the typical structure of real supply chains. The reduction to a standard TP is elegant: by duplicating each transshipment node and adding a zero-cost self-loop (goods that don't transship \"stay\" at the node), we convert the problem into a standard TP that any TP solver can handle. This reduction is important: it means that transshipment problems are no harder than transportation problems computationally.\n:::\n\n---\n\n## Transshipment — Mathematical Model\n\n**Extended formulation with transshipment nodes:**\n\nFor transshipment node $t \\in V_t$, let $\\bar{y}_t$ = amount **not** transshipped (= amount that \"loops\" through the dummy):\n\n::: {.columns}\n::: {.column width=\"55%\"}\n**Flow balance at transshipment node $t$:**\n\n$$\\sum_{i \\in V_a \\cup V_t} x_{it} + \\bar{y}_t = L$$\n\n$$\\sum_{j \\in V_t \\cup V_d} x_{tj} + \\bar{y}_t = L$$\n\nWhere $L = \\sum_{k \\in V_a} a_k$ (total supply).\n\n**Expanded cost matrix:** Insert cost $M = \\infty$ (large penalty) for forbidden direct routes. Insert cost $0$ for self-loops at transshipment nodes.\n\n**Result:** A standard $|V_a| + |V_t|$ by $|V_t| + |V_d|$ TP problem.\n:::\n::: {.column width=\"45%\"}\n**Example network:**\n\n- $|V_a| = 3$ supply nodes (capacity $a_i$)\n- $|V_t| = 3$ transshipment hubs\n- $|V_d| = 3$ demand nodes\n\n**Expanded TP size:**\n\n$(3+3) \\times (3+3) = 6 \\times 6$ matrix\n\n- Supply row for each original supply node ($a_i$) + each transshipment node ($L$)\n- Demand column for each transshipment node ($L$) + each demand node ($b_j$)\n\nFeasibility: $\\sum a_i = \\sum b_j$ must hold (balance with dummy if needed).\n:::\n:::\n\n::: {.notes}\nThe expanded matrix can become large quickly when there are many transshipment nodes — a 10-hub network with 50 origins and 200 destinations would create a very large matrix. In practice, modern LP solvers handle this efficiently by exploiting the sparse network structure. Multi-commodity transshipment problems (multiple product types sharing the same network) are significantly harder and require more advanced solvers.\n:::\n\n---\n\n## Transshipment Example\n\n**3 production sites → 3 hubs → 3 demand sites**\n\n**$L = \\sum a_i = 6 + 5 + 9 = 20$**\n\n**Original cost data:**\n\n| | Hub 1 | Hub 2 | Hub 3 |\n|--|-------|-------|-------|\n| P1 (cap=6) | 2 | 3 | 1 |\n| P2 (cap=5) | 5 | 4 | 8 |\n| P3 (cap=9) | 6 | 2 | 7 |\n\n| | Demand 1 | Demand 2 | Demand 3 |\n|--|---------|---------|---------|\n| Hub 1 (req=8) | 6 | 3 | 5 |\n| Hub 2 (req=7) | 4 | 8 | 2 |\n| Hub 3 (req=5) | 3 | 7 | 6 |\n\n**Expanded 6×6 TP:** Row capacities: [6, 5, 9, 20, 20, 20]; Column demands: [20, 20, 20, 8, 7, 5].\n\nUse VAM or R/`lp.transport()` on the expanded matrix. Self-loops (Hub $i$ → Hub $i$) have cost 0; other Hub-Hub flows = $M$.\n\n::: {.notes}\nWalk through the reduction step by step. The 6×6 expanded matrix has the original 3×3 cost blocks (P→Hub, Hub→Demand) plus forbidden blocks (P→Demand with cost M, Hub→Hub with M except 0 on diagonal). The self-loop columns absorb the \"unneeded\" capacity at each hub. The solution will show which hubs route which flows and how much flows directly from each hub. Total cost excludes the dummy self-loop costs (which are 0 anyway).\n:::\n\n---\n\n## R Code — Transshipment Problem\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lpSolve)\n\n# Parameters\nL <- 20  # total supply\nM <- 9999  # large penalty for forbidden routes\n\n# Expanded cost matrix (6x6)\n# Rows:    P1, P2, P3, Hub1, Hub2, Hub3\n# Columns: Hub1, Hub2, Hub3, D1, D2, D3\ncosts_exp <- matrix(c(\n  # P1→Hubs       P1→Demands\n   2,  3,  1,     M, M, M,\n  # P2\n   5,  4,  8,     M, M, M,\n  # P3\n   6,  2,  7,     M, M, M,\n  # Hub1→Hubs (self-loop=0)  Hub1→Demands\n   0,  M,  M,     6, 3, 5,\n  # Hub2\n   M,  0,  M,     4, 8, 2,\n  # Hub3\n   M,  M,  0,     3, 7, 6\n), nrow = 6, byrow = TRUE)\n\nsupply_exp <- c(6, 5, 9, L, L, L)\ndemand_exp <- c(L, L, L, 8, 7, 5)\n\nsol <- lp.transport(costs_exp, \"min\",\n                    rep(\"<=\", 6), supply_exp,\n                    rep(\">=\", 6), demand_exp)\n\ncat(\"Optimal transport cost:\", sol$objval - 0, \"\\n\")\n# Note: subtract any dummy costs if applicable\nflow <- matrix(sol$solution, 6, 6, byrow = FALSE)\n```\n:::\n\n\n::: {.callout-tip title=\"Interpretation\"}\n- Flows in the top-left $3\\times3$ block: direct plant-to-hub assignments\n- Flows in the bottom-right $3\\times3$ block: hub-to-demand assignments\n- Self-loop flows (diagonal of hub block): unused hub capacity\n- Total cost = sum of real route costs only (self-loop cost = 0)\n:::\n\n::: {.notes}\nRun this live. Encourage students to modify the network: what if Hub 1 is down (set all Hub 1 columns to M)? What if demand at D1 doubles? How does the solution change? This type of sensitivity analysis is crucial for building resilient supply chain plans. The code can be easily adapted to solve any transshipment network by modifying the cost matrix and capacity vectors.\n:::\n\n---\n\n## Key Takeaways — Module 3\n\n::: {.columns}\n::: {.column width=\"60%\"}\n**Core concepts:**\n\n1. Transport is typically 40–70% of total logistics cost — small percentage improvements are highly valuable\n\n2. **Mode selection** is driven by value density, time sensitivity, and volume — not just price\n\n3. The **Transportation Problem** is an LP with a totally unimodular constraint matrix → always integer optimal, solvable in milliseconds\n\n4. **VAM** provides near-optimal initial solutions (typically within 5%) through regret-based allocation — useful for warm-starts and manual verification\n\n5. **Transshipment** extends TP to multi-echelon networks and reduces to a standard TP via node duplication\n\n6. R/`lpSolve` solves real-world TP/transshipment instances in seconds — heuristics remain relevant for real-time and online decisions\n:::\n::: {.column width=\"40%\"}\n**Coming up — Module 4:**\n\n- Demand forecasting methods\n  - Moving average, exponential smoothing\n  - Regression, seasonal decomposition\n- Forecast accuracy metrics (MAE, MAPE, RMSE)\n- The Bullwhip Effect\n- Safety stock and service levels\n\n**Preparation:**\n\n- Read Chopra & Meindl, Chapter 7 (Demand Forecasting)\n- Ensure R with `forecast` and `fable` packages installed\n- Review: mean, variance, normal distribution\n\n**Course project:**\n\nModule 3 exercise (Battery Logistics) forms the basis for the network design module of the course project.\n:::\n:::\n\n::: {.notes}\nSummarise by linking the three modules together: Module 1 provided the conceptual vocabulary (three flows, cycle view, push/pull, planning matrix). Module 2 answered the strategic question \"where?\" (network design, facility location). Module 3 answers the tactical question \"how much flows where?\" (transportation optimisation). The next module will address \"how much to prepare?\" (forecasting and inventory management). This progressive build-up is intentional — each module adds a new decision layer to the supply chain management picture.\n:::\n\n---\n\n## Appendix: VAM Full Step-by-Step {visibility=\"uncounted\"}\n\n**Pear Disk Drive — Complete VAM solution:**\n\n::: {.columns}\n::: {.column width=\"50%\"}\n**Iteration 1:**\n- Regrets: Sioux Falls col = 1240 (max)\n- Cheapest in Sioux Falls col: Sunnyvale (280)\n- Allocate: $x_{Sunnyvale,SF} = \\min(45, 55) = 45$\n- Sunnyvale exhausted; Sioux Falls remaining = 10\n\n**Iteration 2:**\n- Regrets (updated, Sunnyvale row removed)\n- Dublin row regret: $1440-990 = 450$; Bangkok: $1660-1420 = 240$\n- Sioux Falls col regret: $1730-1520 = 210$; Amarillo: $1550-1280 = 270$; Teaneck: $1420-990=430$; Chicago: $1660-1440=220$\n- Max = Dublin row (450)\n- Cheapest in Dublin row = Teaneck (990)\n- Allocate: $x_{Dublin,Teaneck} = \\min(120, 78) = 78$; Teaneck exhausted\n:::\n::: {.column width=\"50%\"}\n**Iterations 3–5:** (continue similarly)\n\n**Final allocation:**\n\n| | Amarillo | Teaneck | Chicago | Sioux Falls |\n|--|---------|---------|---------|------------|\n| Sunnyvale | — | — | — | **45** |\n| Dublin | **32** | **78** | — | **10** |\n| Bangkok | **48** | — | **47** | — |\n\n**Total cost:**\n$$45(280) + 32(1280) + 78(990) + 10(1520) + 48(1550) + 47(1660)$$\n$$= 12{,}600 + 40{,}960 + 77{,}220 + 15{,}200 + 74{,}400 + 78{,}020 = \\$298{,}400$$\n:::\n:::\n\n::: {.notes}\nThe appendix slide is for instructor reference and for students who want to verify their VAM calculations. The optimal LP solution (from lpSolve) is $298,400 — confirming that VAM found the exact optimum on this instance. This is not guaranteed in general but is common for well-structured problems.\n:::\n\n---\n\n## Appendix: R — Complete Battery Logistics Code {visibility=\"uncounted\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lpSolve)\nlibrary(geosphere)  # for Haversine distances\n\n# Coordinates: warehouses and plants (lat, lon)\nwarehouses <- data.frame(\n  name = c(\"Düren\", \"Harsewinkel\", \"Langenhagen\"),\n  lat  = c(50.804, 51.959, 52.440),\n  lon  = c(6.487, 8.237, 9.736),\n  cap  = c(150000, 50000, 100000)\n)\n\nplants <- data.frame(\n  name   = c(\"Wolfsburg\",\"Emden\",\"Hannover\",\"Leipzig\",\"Zwickau\",\n              \"Kassel\",\"Brussels\",\"Ghent\",\"Antwerp\",\"Stuttgart\",\"Munich\"),\n  lat    = c(52.423, 53.367, 52.375, 51.340, 50.730,\n             51.312, 50.846, 51.053, 51.221, 48.775, 48.137),\n  lon    = c(10.786, 7.206, 9.732, 12.374, 12.496,\n             9.479, 4.352, 3.721, 4.399, 9.182, 11.576),\n  demand = c(40000, 20000, 35000, 45000, 30000,\n             25000, 20000, 15000, 20000, 20000, 10000)\n)\n\n# Build cost matrix: cost per MWh = distance (km) × 0.08\ncost_matrix <- matrix(0, nrow(warehouses), nrow(plants))\nfor(i in seq_len(nrow(warehouses))) {\n  for(j in seq_len(nrow(plants))) {\n    dist_km <- distHaversine(\n      c(warehouses$lon[i], warehouses$lat[i]),\n      c(plants$lon[j], plants$lat[j])\n    ) / 1000\n    cost_matrix[i, j] <- dist_km * 0.08\n  }\n}\n\n# Solve transportation problem\nsol <- lp.transport(cost_matrix, \"min\",\n                    rep(\"<=\", 3), warehouses$cap,\n                    rep(\">=\", nrow(plants)), plants$demand)\n\n# Results\nflow <- matrix(sol$solution, nrow = 3)\ndimnames(flow) <- list(warehouses$name, plants$name)\ncat(\"Annual transport cost: €\", round(sol$objval, 0), \"\\n\")\nprint(round(flow, 0))\n```\n:::\n\n\n::: {.notes}\nThis is production-quality code that students can use directly for the course project. The Haversine calculation uses actual GPS coordinates for German/Belgian cities. Encourage students to explore: (1) What is the shadow price of the Harsewinkel capacity constraint? (This tells you the value of expanding that warehouse.) (2) What happens if one warehouse is unexpectedly closed (set capacity to 0)? How much does cost increase? These are resilience analysis questions with direct practical relevance.\n:::\n",
    "supporting": [
      "03_network_design_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}