{
  "hash": "a78c94f4b3493074b58f2971f9e21493",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Module 2: SC Strategy & Network Design\"\nsubtitle: \"SCM — Bachelor 3rd Semester\"\nauthor: \"Prof. Dr. Thomas Kirschstein\"\ndate: last-modified\nformat:\n  revealjs:\n    theme: [default, ../../_extensions/scm-theme.scss]\n    slide-number: true\n    chalkboard: true\n    preview-links: auto\n    footer: \"SCM | Module 2 | HS RheinMain\"\n    transition: slide\n    incremental: false\n    toc: true\n    toc-depth: 1\nexecute:\n  echo: false\n  warning: false\n---\n\n# Part 1: Strategic Fit {background-color=\"#1B2A4A\"}\n\n## Learning Objectives\n\nAfter this module, you will be able to:\n\n- **Explain** the concept of strategic fit between competitive and SC strategy\n- **Position** a supply chain on the responsiveness–efficiency spectrum\n- **Apply** the SC drivers framework to design decisions\n- **Formulate** facility location problems using weighted scoring and AHP\n- **Solve** the Steiner-Weber model and the Warehouse Location Problem\n- **Identify** trade-offs between centralisation and decentralisation\n\n::: {.notes}\nModule 2 bridges conceptual strategy (Part 1) with quantitative methods (Parts 2–3). Stress to students that the strategic fit concept motivates *why* we design networks in particular ways — the quantitative methods then tell us *how* to do it optimally. Both halves are needed.\n:::\n\n---\n\n## Competitive Strategy and SC Strategy\n\n**A firm's competitive strategy defines the customer value proposition:**\n\n| Competitive Strategy | SC Implication | Key SC Capability |\n|---------------------|----------------|-------------------|\n| **Cost leadership** | Efficient SC | High utilisation, lean inventory |\n| **Innovation leadership** | Responsive SC | Fast time-to-market, flexible capacity |\n| **Service leadership** | Customer-tailored SC | High variety, reliability, customisation |\n| **Quality leadership** | Reliable, controlled SC | Low defect rate, supplier quality management |\n| **Sustainability leadership** | Green SC | Low CO₂, circular flows, transparent sourcing |\n\n::: {.callout-note title=\"Strategic Fit (Chopra & Meindl)\"}\n**Strategic Fit** exists when the SC strategy supports the competitive strategy — i.e., the supply chain is designed and managed to achieve the level of **responsiveness** that the target customer segment values and is willing to pay for.\n\nLack of strategic fit is one of the most common causes of SC underperformance.\n:::\n\n::: {.notes}\nAsk students to think of a firm where the competitive strategy and SC strategy are clearly misaligned. Classic example: a luxury brand that outsources to the cheapest possible supplier to cut costs — the quality deteriorates and the brand promise is broken. Strategic fit is not just an academic concept; it is a discipline that prevents this kind of erosion.\n:::\n\n---\n\n## The Responsiveness–Efficiency Spectrum\n\n::: {.columns}\n::: {.column width=\"60%\"}\n**Conceptual framework:**\n\n```\nSC Responsiveness\n    ↑\n    │  ●  Fashion / luxury        ← Responsive SC\n    │     (High uncertainty)\n    │\n    │        ● Computers / CE\n    │              (Medium-high)\n    │\n    │                ● Furniture\n    │                   (Medium-low)\n    │\n    │                       ● Staples / commodities\n    │                           (Low uncertainty)\n    └─────────────────────────────────────────→\n                Demand Uncertainty\n```\n\n**Zone of Strategic Fit**: the diagonal band.\nAbove → over-investment in responsiveness.\nBelow → SC too rigid for the market.\n:::\n::: {.column width=\"40%\"}\n**Implied demand uncertainty** is high when:\n\n- Products have short life cycles\n- High variety / customisation required\n- Demand is difficult to forecast\n- Customer lead time tolerance is very short\n- High product innovation rate\n\n**Implied demand uncertainty** is low when:\n\n- Commodity-like, standard products\n- Long-standing, stable demand\n- Price-driven purchase decision\n- Customer willing to wait (MTO)\n:::\n:::\n\n::: {.notes}\nThe Responsive–Efficient spectrum is the diagnostic framework. Before any network design decision, ask: \"What does the market require?\" Only then can you evaluate whether your SC delivers the right level of responsiveness. A common mistake is companies applying lean/efficient principles to high-uncertainty products — the result is chronic stockouts and lost sales.\n:::\n\n---\n\n## SC Drivers Framework\n\n**Five drivers determine the responsiveness–efficiency position** (Chopra & Meindl):\n\n| Driver | Efficient (Low Cost) | Responsive (High Service) |\n|--------|---------------------|---------------------------|\n| **Production** | Few plants, high utilisation, narrow product range | Many plants, excess capacity, broad range |\n| **Inventory** | Low levels, few SKUs | High safety stock, full SKU coverage everywhere |\n| **Location** | Centralised, few sites near cheap supply | Dense network, proximity to customers |\n| **Transportation** | Full truckloads, slow modes, long cycles | Frequent, fast, flexible; express capability |\n| **Information** | Shared selectively, batch-based | Deep real-time integration (EDI, API, IoT) |\n\n::: {.callout-tip title=\"Management Principle\"}\nEach driver is a **lever**. Shifting a driver toward responsiveness increases service but also increases cost. The art of SC design is choosing the right combination of driver settings given the strategic fit requirement.\n\nThere is no universally optimal setting — **context determines configuration**.\n:::\n\n::: {.notes}\nWalk through each driver with a concrete example. For inventory: Amazon holds ~40 days of inventory in its fulfillment centres (high service) while Aldi runs on ~10 days (low cost, standard products). For location: DHL has 400+ service points in Germany (responsive) while a steel manufacturer ships from 2 plants in Europe (efficient). The drivers framework provides a structured vocabulary for SC design discussions.\n:::\n\n---\n\n## Examples — Strategic Fit in Practice\n\n::: {.columns}\n::: {.column width=\"50%\"}\n**Zara (Inditex)**\n\n- **Strategy**: Fast fashion → Responsive SC\n- In-house European production (Spain, Portugal)\n- 2-week design-to-shelf (industry avg: 6 months)\n- Accepts ~30% higher cost vs. offshore competitors\n- Replenishes stores twice per week\n- Result: <1% items marked down (industry: 30–40%)\n\n**H&M**\n\n- **Strategy**: Hybrid — price leadership + style\n- Offshore for basics (efficient)\n- Near-shore for fast-fashion lines (responsive)\n- Longer lead times, more markdowns → different margin structure\n:::\n::: {.column width=\"50%\"}\n**Amazon**\n\n- **Strategy**: Service leadership → Dense responsive network\n- 200+ fulfillment centres in Europe alone\n- Multi-layer: large FCs → sortation centres → DSPs → last-mile\n- Pays for speed with massive fixed-cost infrastructure\n- Prime delivery time commitment drives entire network design\n\n**IKEA**\n\n- **Strategy**: Cost leadership → Efficient SC\n- Standardised products (flat-pack maximises cube utilisation)\n- Global low-cost sourcing (mainly Asia, Eastern Europe)\n- Store = DC (customer does last-mile themselves)\n- Very low inventory cost per unit of revenue\n:::\n:::\n\n::: {.notes}\nThese four examples span the full spectrum. Ask students: \"If Zara tried to copy IKEA's cost model, what would break?\" They would lose their speed advantage — their competitive strategy depends on the responsive SC. And vice versa: IKEA cannot go responsive without destroying its price proposition. Strategic fit is not optional; it is the foundation of competitive advantage.\n:::\n\n---\n\n# Part 2: Location Planning Methods {background-color=\"#1B2A4A\"}\n\n## Facility Location — The Strategic Decision\n\n::: {.columns}\n::: {.column width=\"55%\"}\n**Why location decisions are special:**\n\n- **Long-term irreversible** → high switching costs, path dependencies\n- **Multi-dimensional** → qualitative (labour market, regulation, infrastructure) AND quantitative (transport cost, demand coverage)\n- **Multi-level** → global region → country → city → specific site\n- **Context-dependent** → a DC location differs fundamentally from a plant location\n\n**Key question:**\n\n*Where do we place factories, distribution centres, and stores to best serve customers at minimum total cost?*\n:::\n::: {.column width=\"45%\"}\n**Relevant cost components:**\n\n```\nTotal Network Cost\n  = Σ Fixed facility costs\n  + Σ Variable production / handling costs\n  + Σ Inbound transport costs\n  + Σ Outbound transport costs\n  + Σ Inventory holding costs\n  − Σ Revenue effects\n    (proximity → faster delivery → higher demand)\n```\n\nLocation decisions affect **all** cost components simultaneously.\n:::\n:::\n\n::: {.notes}\nLocation decisions are made infrequently — perhaps once per decade for a major facility — but they have consequences that last for the entire planning horizon. The 2022 energy crisis forced many German manufacturers to reconsider their facility locations because German energy costs suddenly became prohibitive. A DC built in 2015 assuming cheap energy looked very different economically by 2023. This illustrates the long-term, irreversible nature of location decisions.\n:::\n\n---\n\n## Classification of Location Methods\n\n| Method | Decision Space | # Facilities | Criteria Type |\n|--------|---------------|-------------|---------------|\n| **Weighted Scoring** *(Nutzwertanalyse)* | Discrete (given options) | Multiple | Multi-criteria |\n| **Analytic Hierarchy Process (AHP)** | Discrete | Multiple | Multi-criteria |\n| **Steiner-Weber (Euclidean)** | Continuous | Single | Single cost |\n| **Steiner-Weber (Manhattan)** | Continuous | Single | Single cost |\n| **Set Covering Model** | Discrete | Multiple | Single service |\n| **Max. Covering (MCLP)** | Discrete | Multiple | Single service |\n| **Warehouse Location Problem (WLP)** | Discrete | Multiple | Single cost |\n\n**Two fundamental dimensions:**\n\n- *Discrete* vs. *Continuous*: Is the solution space a finite set of candidates or all of ℝ²?\n- *Single-* vs. *Multi-criteria*: Is cost the only objective, or are qualitative factors included?\n\n::: {.notes}\nThe choice of method depends on the problem structure and data availability. In practice, a two-stage approach is common: first use a qualitative method (AHP) to shortlist to 3–5 candidates, then use a quantitative model (WLP) to select the optimal set. The pure continuous models (Steiner-Weber) are useful for initial orientation but rarely used as the final decision tool.\n:::\n\n---\n\n## Weighted Scoring (Nutzwertanalyse)\n\n**Step-by-step procedure:**\n\n1. **Define evaluation criteria** relevant to the location decision\n2. **Assign weights** to criteria: $\\sum_k w_k = 1$\n3. **Score each alternative** on each criterion (scale: 1–10 or 0–100)\n4. **Calculate weighted score** for each alternative:\n   $$S(i) = \\sum_k w_k \\cdot s_k(i)$$\n5. **Rank alternatives** by $S(i)$; select highest-scoring option\n\n**Example structure:**\n\n| Criterion | Weight | Site A | Site B | Site C |\n|-----------|--------|--------|--------|--------|\n| Labour market | 0.25 | 7 | 5 | 8 |\n| Infrastructure | 0.30 | 8 | 9 | 6 |\n| Proximity to customers | 0.35 | 6 | 7 | 9 |\n| Regulatory environment | 0.10 | 9 | 8 | 7 |\n| **Weighted Score** | | **7.10** | **7.15** | **7.75** |\n\n::: {.callout-warning title=\"Limitations\"}\n- Assumes full **compensability** (a bad score on one criterion can be offset by a good score on another)\n- **Weight determination** is subjective and politically sensitive\n- **Scale dependency**: converting qualitative assessments to numbers introduces measurement error\n:::\n\n::: {.notes}\nThe Nutzwertanalyse is widely used in practice, especially in German-speaking countries, precisely because it is transparent and auditable. The weights and scores are documented and can be reviewed. The main criticism is the compensability assumption — in some decisions, a fatal flaw on one dimension should disqualify a site regardless of other scores. In such cases, use hard constraints to eliminate dominated alternatives before applying the scoring.\n:::\n\n---\n\n## Analytic Hierarchy Process (AHP)\n\n**AHP improves on weighted scoring by deriving weights via pairwise comparisons:**\n\n::: {.columns}\n::: {.column width=\"55%\"}\n**Procedure:**\n\n1. Build pairwise comparison matrix for **criteria**: \"How much more important is criterion A than criterion B?\"\n2. Use Saaty scale (1 = equal, 3 = moderate, 5 = strong, 7 = very strong, 9 = extreme)\n3. Derive criteria **priority vector** (eigenvector of comparison matrix)\n4. Repeat pairwise comparisons for **alternatives** under each criterion\n5. Compute **global priority** = weighted sum of local priorities\n\n**Key advantage — Consistency Check:**\n\n$$CI = \\frac{\\lambda_{max} - n}{n - 1}, \\quad CR = \\frac{CI}{RI}$$\n\n- $\\lambda_{max}$: principal eigenvalue\n- $RI$: random index (tabulated by matrix size)\n- $CR < 0.10$ → judgments are acceptably consistent\n- $CR > 0.10$ → revisit pairwise comparisons\n:::\n::: {.column width=\"45%\"}\n**Saaty scale:**\n\n| Value | Interpretation |\n|-------|---------------|\n| 1 | Equal importance |\n| 3 | Moderate importance |\n| 5 | Strong importance |\n| 7 | Very strong |\n| 9 | Extreme importance |\n| 2,4,6,8 | Intermediate values |\n\n**Random Index (RI) by matrix size:**\n\n| n | 3 | 4 | 5 | 6 |\n|---|---|---|---|---|\n| RI | 0.58 | 0.90 | 1.12 | 1.24 |\n:::\n:::\n\n::: {.notes}\nAHP was developed by Thomas Saaty at the University of Pittsburgh in the 1970s and is one of the most widely cited decision-making methods globally. The consistency ratio is its key innovation — it catches logical inconsistencies in human judgment. If a decision maker says \"A is better than B, B is better than C, but C is better than A\", the consistency check will flag this. Practical point: AHP is implemented in many decision support tools and can be exported from Excel add-ins.\n:::\n\n---\n\n## AHP Example — Shopping Centre Location\n\n**Three candidate sites (A, B, C); four criteria:**\n\n| Criterion | Weight | Interpretation |\n|-----------|--------|---------------|\n| Customer market size | 0.199 | Total addressable spending within 30 min drive |\n| Customer accessibility | **0.654** | Public transport + parking + road access |\n| Infrastructure quality | 0.086 | Building condition, tech infrastructure |\n| Transport access | 0.061 | Delivery logistics, supplier accessibility |\n\n**Local priority scores (from pairwise comparisons per criterion):**\n\n| Site | Market | Access | Infra. | Transport | **Global Score** |\n|------|--------|--------|--------|-----------|-----------------|\n| A | 0.558 | 0.153 | 0.633 | 0.122 | **0.241** |\n| B | 0.321 | 0.260 | 0.260 | 0.320 | **0.268** |\n| **C** | 0.122 | **0.587** | 0.106 | 0.558 | **0.490** ✓ |\n\n::: {.callout-tip title=\"Management Lesson\"}\n**Site C wins** — despite having the smallest customer market, its dominant advantage on *customer accessibility* (weight = 0.654) overwhelms the other criteria.\n\nAHP makes trade-offs **explicit and auditable**, reducing \"gut feeling\" bias and political manipulation. The weights force decision makers to confront their true priorities.\n:::\n\n::: {.notes}\nWalk through the calculation for Site C: 0.199×0.122 + 0.654×0.587 + 0.086×0.106 + 0.061×0.558 = 0.024 + 0.384 + 0.009 + 0.034 = 0.490 ✓. Ask students: \"Why does accessibility dominate so heavily?\" Because a shopping centre with great products but hard to reach has an insurmountable competitive disadvantage. The AHP just makes this intuition rigorous.\n:::\n\n---\n\n## Steiner-Weber Model — Continuous Location\n\n**Problem:** Find location $(x, y)$ minimising weighted total transport distance to $n$ customer sites.\n\n$$\\min_{x, y} \\; Z(x, y) = \\sum_{i=1}^{n} a_i \\cdot d\\!\\left((x, y),\\, (u_i, v_i)\\right)$$\n\n**Where:**\n\n- $(u_i, v_i)$ = coordinates of customer site $i$\n- $a_i$ = demand weight at site $i$ (tonnes/year, shipments/year, etc.)\n- $d$ = distance function:\n  - **Euclidean:** $d = \\sqrt{(x-u_i)^2 + (y-v_i)^2}$\n  - **Manhattan (rectilinear):** $d = |x-u_i| + |y-v_i|$\n\n::: {.callout-note title=\"When to use Steiner-Weber\"}\n- Single-facility location in a region (one DC for a country, one plant for a market)\n- Demand concentrated at discrete points (customers, cities)\n- Transport cost proportional to distance and volume\n- Provides **initial orientation** before discrete network models are applied\n:::\n\n::: {.notes}\nThe Steiner-Weber problem dates to 1909 (Weber's location theory) and is the classical model of industrial location theory. It assumes a flat plane, which is only an approximation of reality — road networks are not Euclidean. However, for large geographic scales (country-level), the approximation is often acceptable. The Manhattan metric is appropriate when transport follows a grid pattern (urban settings, North American city grids).\n:::\n\n---\n\n## Steiner-Weber — Solution Approaches\n\n::: {.columns}\n::: {.column width=\"55%\"}\n**1. Center of Gravity (CoG)**\n\nQuick approximation — minimises *sum of squared distances* (not Euclidean):\n\n$$x^{CoG} = \\frac{\\sum_i a_i u_i}{\\sum_i a_i}, \\quad y^{CoG} = \\frac{\\sum_i a_i v_i}{\\sum_i a_i}$$\n\nFast, interpretable, but **not optimal** for Euclidean distances.\n\n**2. Weiszfeld Algorithm** *(for Euclidean — iterative)*\n\nIterate until convergence (start from CoG):\n\n$$x^{(t+1)} = \\frac{\\sum_i \\frac{a_i \\, u_i}{d_i^{(t)}}}{\\sum_i \\frac{a_i}{d_i^{(t)}}}, \\quad y^{(t+1)} = \\frac{\\sum_i \\frac{a_i \\, v_i}{d_i^{(t)}}}{\\sum_i \\frac{a_i}{d_i^{(t)}}}$$\n\nwhere $d_i^{(t)} = d\\!\\left((x^{(t)}, y^{(t)}),\\, (u_i, v_i)\\right)$.\n\nGuaranteed to converge (unless a customer site is optimal).\n\n**3. Manhattan Optimal Solution**\n\nSolve **independently per coordinate**: optimal = weighted median of $u_i$ (and separately $v_i$).\n:::\n::: {.column width=\"45%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](02_strategy_files/figure-revealjs/unnamed-chunk-1-1.png){width=384}\n:::\n:::\n\n:::\n:::\n\n::: {.notes}\nThe Weiszfeld algorithm is a classic example of an iterative re-weighted least squares method. In the weighted median interpretation for Manhattan distance: sort customer sites by u-coordinate, find the site where cumulative demand first exceeds 50% of total demand — that is the optimal x-coordinate. Same for y. This gives an exact solution for Manhattan in O(n log n) time.\n:::\n\n---\n\n## Exercise 2.1 — Center of Gravity {background-color=\"#1e2a38\"}\n\n**Five customer locations with annual demands:**\n\n| Site | x | y | Demand (t/yr) |\n|------|---|---|--------------|\n| A | 2 | 8 | 500 |\n| B | 7 | 3 | 300 |\n| C | 5 | 6 | 800 |\n| D | 1 | 2 | 200 |\n| E | 9 | 7 | 400 |\n\n**Tasks:**\n\n1. Calculate the **Center of Gravity** $(x^{CoG}, y^{CoG})$\n2. Apply **one Weiszfeld iteration** starting from CoG:\n   - Calculate $d_i^{(0)}$ for each site (Euclidean distance from CoG)\n   - Apply the Weiszfeld update formula to get $(x^{(1)}, y^{(1)})$\n3. Does $(x^{(1)}, y^{(1)})$ improve on the CoG? Calculate $Z$ at both points.\n4. *Extension*: Find the optimal **Manhattan** location using the weighted median approach.\n\n::: {.callout-tip title=\"Hint\"}\nTotal demand: $\\sum a_i = 2200$ t/yr.\n:::\n\n::: {.notes}\nExpected CoG: x = (500×2 + 300×7 + 800×5 + 200×1 + 400×9)/2200 = (1000+2100+4000+200+3600)/2200 = 10900/2200 = 4.955. y = (500×8 + 300×3 + 800×6 + 200×2 + 400×7)/2200 = (4000+900+4800+400+2800)/2200 = 12900/2200 = 5.864. For the weighted median: sort by x: D(1), A(2), C(5), B(7), E(9). Cumulative demands: 200, 700, 1500, 1800, 2200. 50% of 2200 = 1100. First exceeds at C (1500 > 1100), so optimal x = 5. Similarly for y.\n:::\n\n---\n\n# Part 3: Network Planning Models {background-color=\"#1B2A4A\"}\n\n## Distribution Network Design\n\n**The fundamental trade-off in network design:**\n\n::: {.columns}\n::: {.column width=\"60%\"}\n**More locations → Higher fixed costs, lower transport costs**\n\n$$TC(n) = \\underbrace{n \\cdot f}_{\\text{fixed cost}} + \\underbrace{g(n)}_{\\text{transport cost}}$$\n\nwhere $g(n)$ decreases in $n$ (shorter average distance to customers).\n\n**→ An optimal number of facilities $n^*$ exists.**\n\nThe optimal $n^*$ depends on:\n- Ratio of fixed to variable transport cost\n- Spatial distribution of demand\n- Required service level (max delivery time)\n- Product characteristics (weight, value density)\n:::\n::: {.column width=\"40%\"}\n```\nTotal Cost\n    ↑\n    │ TC = Fixed + Transport\n    │     ╲___________╱\n    │      ╲         ╱\n    │       ╲       ╱\n    │  Fixed─╲─────╱── \n    │  Cost   ╲   /\n    │  Transport╲╱\n    │            n*         → n (# locations)\n```\n\n**Network design** = selecting *which* facilities to open AND *which* customers to assign to each.\n:::\n:::\n\n::: {.notes}\nThis cost trade-off is the fundamental insight of network design theory. In practice, companies often have too many or too few facilities based on historical path dependencies rather than optimisation. German manufacturers that grew through acquisition often end up with 8–10 redundant small DCs that could be consolidated into 3 efficient ones. Network rationalisation programs regularly deliver 15–25% logistics cost savings.\n:::\n\n---\n\n## Covering Location Models\n\n::: {.columns}\n::: {.column width=\"50%\"}\n**Set Covering Problem (SCP):**\n\n*Minimise the number of facilities to cover all demand within service radius $D$.*\n\n$$\\min \\sum_j y_j \\quad \\text{s.t.} \\quad \\sum_{j: d_{ij} \\leq D} y_j \\geq 1 \\; \\forall i$$\n\n- $y_j \\in \\{0,1\\}$: open facility at site $j$\n- NP-hard, but good approximation via LP-relaxation or greedy heuristic\n\n**Maximum Covering (MCLP):**\n\n*Given budget of $p$ facilities, maximise covered demand.*\n\n$$\\max \\sum_i b_i z_i \\quad \\text{s.t.} \\quad \\sum_j y_j \\leq p, \\; z_i \\leq \\sum_{j:d_{ij}\\leq D} y_j$$\n\n- $z_i \\in \\{0,1\\}$: demand node $i$ covered\n- $b_i$ = demand volume at node $i$\n:::\n::: {.column width=\"50%\"}\n**Applications:**\n\n- Emergency service location (ambulances, fire stations)\n- Retail store network with service radius guarantee\n- Mobile phone tower placement\n- Vaccine distribution centres\n\n**Greedy Heuristic for MCLP:**\n\n```\nMCLP_Greedy(p):\n  open_set = {}\n  for k = 1 to p:\n    best_j = argmax over j ∉ open_set of:\n               marginal demand covered by j\n    open_set = open_set ∪ {best_j}\n    update covered demand set\n  return open_set\n```\n\nPerformance guarantee: $1 - (1 - 1/p)^p \\approx 0.63$ of optimal.\n:::\n:::\n\n::: {.notes}\nThe MCLP was introduced by Church & ReVelle (1974) and is one of the most cited facility location models. The greedy heuristic has a well-known theoretical performance bound. In practice, commercial solvers (CPLEX, Gurobi) can solve instances with hundreds of candidate locations and thousands of demand nodes to optimality in minutes. The covering models are particularly relevant for public service planning and retail expansion.\n:::\n\n---\n\n## Warehouse Location Problem (WLP)\n\n**Given:**\n\n- Set $J$ of potential warehouse locations with **fixed opening costs** $f_j$\n- Set $I$ of customers with **demands** $d_i$\n- **Unit transport costs** $c_{ij}$ per unit from warehouse $j$ to customer $i$\n\n**Decide:** Which warehouses to open ($y_j$) and how to assign customers to open warehouses ($x_{ij}$).\n\n**MILP Formulation:**\n\n$$\\min \\sum_{j \\in J} f_j y_j + \\sum_{i \\in I}\\sum_{j \\in J} c_{ij} x_{ij}$$\n\nSubject to:\n\n$$\\sum_{j \\in J} x_{ij} = d_i \\quad \\forall i \\in I \\quad \\text{(demand fulfillment)}$$\n\n$$x_{ij} \\leq d_i \\cdot y_j \\quad \\forall i \\in I, j \\in J \\quad \\text{(only open warehouses serve customers)}$$\n\n$$y_j \\in \\{0,1\\\\}, \\quad x_{ij} \\geq 0$$\n\n::: {.notes}\nThe WLP (also called the Uncapacitated Facility Location Problem, UFLP) is NP-hard in general but has very tight LP relaxations — branch-and-bound methods solve practical instances quickly. The capacitated variant (CFLP) adds capacity limits on each warehouse, making it harder but more realistic. Commercial solvers handle CFLP instances with hundreds of potential locations in seconds. For very large instances (thousands of locations), Lagrangian relaxation heuristics are used.\n:::\n\n---\n\n## WLP Heuristics — Add and Drop\n\n::: {.columns}\n::: {.column width=\"50%\"}\n**Add Heuristic** *(Kühn & Hamburger, 1963)*\n\n```\nADD():\n  open_set = {}   # start: no warehouses open\n  while improvement:\n    savings_j = Σ max(0, current_cost_i\n                      - cost_from_j_i)\n                - f_j    for all j ∉ open_set\n    best_j = argmax savings_j\n    if savings_best > 0:\n      open_set ∪= {best_j}\n      reassign customers optimally\n    else: STOP\n  return open_set\n```\n\n**Typical performance:** 2–5% above optimal for well-structured instances.\n:::\n::: {.column width=\"50%\"}\n**Drop Heuristic** *(Feldman, Lehrer & Ray, 1966)*\n\n```\nDROP():\n  open_set = J   # start: ALL warehouses open\n  while improvement:\n    cost_increase_j = cost_increase if j\n                      is closed  for all j\n    worst_j = argmin cost_increase_j\n    if cost_increase_worst < 0:\n      open_set \\ = {worst_j}\n      reassign affected customers\n    else: STOP\n  return open_set\n```\n\n**Neither guarantees optimality.** Combined Add+Drop heuristic: run Add, then refine with Drop passes.\n:::\n:::\n\n::: {.callout-tip title=\"Practical Guidance\"}\n**Add** tends to find cheaper solutions for sparse networks; **Drop** can get stuck in local optima where interaction effects between warehouses are complex. For real applications, use a commercial MILP solver if $|I| \\times |J| < 10^6$ — it will find the optimum in seconds and the heuristics are unnecessary.\n:::\n\n::: {.notes}\nThe Add and Drop heuristics are important historically and conceptually, but in modern practice they are rarely used because MILP solvers have become fast enough to handle realistic problem sizes. However, they are important for students to understand because (1) they illustrate greedy construction logic, (2) they reveal why the order of decisions matters, and (3) they provide a baseline for evaluating more sophisticated meta-heuristics.\n:::\n\n---\n\n## Exercise 2.2 — WLP with Add Heuristic {background-color=\"#1e2a38\"}\n\n**5 potential warehouses, 7 customers. Fixed costs (€1,000/yr):** $f = [5, 7, 5, 6, 4]$\n\n**Transport cost matrix $c_{ij}$ (€/unit per year):**\n\n| Customer\\Warehouse | W1 | W2 | W3 | W4 | W5 |\n|--------------------|----|----|----|----|-----|\n| C1 (demand=100) | 8 | 2 | 7 | 5 | 9 |\n| C2 (demand=80) | 4 | 6 | 3 | 7 | 5 |\n| C3 (demand=120) | 9 | 4 | 2 | 6 | 3 |\n| C4 (demand=60) | 6 | 8 | 5 | 3 | 7 |\n| C5 (demand=90) | 3 | 5 | 8 | 4 | 6 |\n| C6 (demand=70) | 7 | 3 | 6 | 8 | 2 |\n| C7 (demand=110) | 5 | 7 | 4 | 2 | 8 |\n\n**Tasks:**\n\n1. Apply the **Add Heuristic** — which warehouse opens first? Second? When does the heuristic stop?\n2. Apply the **Drop Heuristic** — same question in reverse\n3. Compare total costs of both solutions\n4. *Extension*: Solve with R (`ompr` or `lpSolve`) and compare to optimal\n\n::: {.notes}\nFor the Add heuristic, start with no warehouses. Each customer is served at infinite cost (or from the most expensive option). Compute marginal savings for opening each warehouse. W3 and W5 typically open early due to covering multiple customers cheaply. Expected optimal solution: open W3 and W5, total cost = 5000 + 4000 + [transport costs]. Walk through the first step with students to ensure they understand the marginal savings calculation, then let them continue in pairs.\n:::\n\n---\n\n## Key Takeaways — Module 2\n\n::: {.columns}\n::: {.column width=\"60%\"}\n**Core concepts:**\n\n1. **Strategic fit** aligns SC design with competitive positioning — the responsive–efficient spectrum is the diagnostic framework\n\n2. **Five SC drivers** (production, inventory, location, transportation, information) are the levers for positioning on the spectrum\n\n3. **Location decisions** are irreversible — use systematic methods (AHP, Nutzwertanalyse) to make trade-offs explicit\n\n4. **AHP** makes subjective preferences explicit, measurable, and consistent — the consistency ratio is a critical quality check\n\n5. **Steiner-Weber / CoG** for single-facility continuous problems; **WLP** for discrete multi-facility network design\n\n6. **Add/Drop heuristics** provide good solutions fast; commercial solvers find optimal solutions for realistic problem sizes\n:::\n::: {.column width=\"40%\"}\n**Coming up — Module 3:**\n\n- Transportation Problem\n- Vogel's Approximation Method (VAM)\n- Transshipment Problem\n- R code for LP-based transport planning\n\n**Preparation:**\n\n- Read Chopra & Meindl, Chapter 5 (Network Design in the SC)\n- Review linear programming fundamentals (LP formulation, simplex concept)\n- Install `lpSolve` package in R: `install.packages(\"lpSolve\")`\n:::\n:::\n\n::: {.notes}\nSummarise by linking back to Module 1: the strategic decisions made in Module 2 (network design, location, strategic fit) operate at the strategic planning horizon. They set the context for the tactical and operational decisions we will study in Modules 3 and 4 (transport planning, demand forecasting, inventory management). A well-designed network is a prerequisite for operational efficiency.\n:::\n",
    "supporting": [
      "02_strategy_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}